ALTER TABLE APEXFRAMEWORK.AFW_01_ATRIB_MODL_COMNC
  DROP CONSTRAINT AFW_01_ATRIB_MODL_COMNC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_ATRIB_MODL_COMNC ADD (
  CONSTRAINT AFW_01_ATRIB_MODL_COMNC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_CODE_ERR_ORACL
  DROP CONSTRAINT AFW_01_CODE_ERR_ORCL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_CODE_ERR_ORACL ADD (
  CONSTRAINT AFW_01_CODE_ERR_ORCL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_CONFG_EVENM_NOTFB
  DROP CONSTRAINT AFW_01_CONFG_EVENM_NOTFB_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_CONFG_EVENM_NOTFB ADD (
  CONSTRAINT AFW_01_CONFG_EVENM_NOTFB_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_DESTN
  DROP CONSTRAINT AFW_01_DESTN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_DESTN ADD (
  CONSTRAINT AFW_01_DESTN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_DESTN_CONFG_EVENM_NOTFB
  DROP CONSTRAINT AFW_01_DESTN_CONFG_EN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_DESTN_CONFG_EVENM_NOTFB ADD (
  CONSTRAINT AFW_01_DESTN_CONFG_EN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_ELEMN_CONFG_EVENM_NOTFB
  DROP CONSTRAINT AFW_01_ELEMN_CONFG_EN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_ELEMN_CONFG_EVENM_NOTFB ADD (
  CONSTRAINT AFW_01_ELEMN_CONFG_EN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_EVENM_NOTFB
  DROP CONSTRAINT AFW_01_EVENM_NOTFB_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_EVENM_NOTFB ADD (
  CONSTRAINT AFW_01_EVENM_NOTFB_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_HIERC_APLIC
  DROP CONSTRAINT AFW_12_HIERC_APLIC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_HIERC_APLIC ADD (
  CONSTRAINT AFW_12_HIERC_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_LANG
  DROP CONSTRAINT AFW_01_LANG_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_LANG ADD (
  CONSTRAINT AFW_01_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_LANG_LANG
  DROP CONSTRAINT AFW_01_LANG_LANG_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_LANG_LANG ADD (
  CONSTRAINT AFW_01_LANG_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_MESG
  DROP CONSTRAINT AFW_01_MESG_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_MESG ADD (
  CONSTRAINT AFW_01_MESG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_MESG_ERR_LIE
  DROP CONSTRAINT AFW_01_MESG_ERR_LIE_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_MESG_ERR_LIE ADD (
  CONSTRAINT AFW_01_MESG_ERR_LIE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_MESG_INFOR
  DROP CONSTRAINT AFW_01_MESG_INFOR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_MESG_INFOR ADD (
  CONSTRAINT AFW_01_MESG_INFOR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_MESG_LANG
  DROP CONSTRAINT AFW_01_MESG_LANG_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_MESG_LANG ADD (
  CONSTRAINT AFW_01_MESG_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_MESG_TRADC_APEX
  DROP CONSTRAINT AFW_01_MESG_TRADC_APEX_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_MESG_TRADC_APEX ADD (
  CONSTRAINT AFW_01_MESG_TRADC_APEX_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_MODL_AFICH_NOTFC
  DROP CONSTRAINT AFW_01_MODL_AFICH_NOTFC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_MODL_AFICH_NOTFC ADD (
  CONSTRAINT AFW_01_MODL_AFICH_NOTFC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_MODL_COMNC
  DROP CONSTRAINT AFW_01_MODL_COMNC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_MODL_COMNC ADD (
  CONSTRAINT AFW_01_MODL_COMNC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_MODL_MESG_NOTFC
  DROP CONSTRAINT AFW_01_MODL_MESG_NOTFC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_MODL_MESG_NOTFC ADD (
  CONSTRAINT AFW_01_MODL_MESG_NOTFC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_NOTFC
  DROP CONSTRAINT AFW_01_NOTFC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_NOTFC ADD (
  CONSTRAINT AFW_01_NOTFC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_OCURN_SA_EVENM_NOTFB
  DROP CONSTRAINT AFW_01_OCURN_SA_EVENM_NOTFB_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_OCURN_SA_EVENM_NOTFB ADD (
  CONSTRAINT AFW_01_OCURN_SA_EVENM_NOTFB_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_PROPG_EVENM_NOTFB
  DROP CONSTRAINT AFW_01_PROPG_EVENM_NOTFB_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_PROPG_EVENM_NOTFB ADD (
  CONSTRAINT AFW_01_PROPG_EVENM_NOTFB_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_RESLT_DESTN
  DROP CONSTRAINT AFW_01_RESLT_DESTN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_RESLT_DESTN ADD (
  CONSTRAINT AFW_01_RESLT_DESTN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_01_TYPE_COMNC
  DROP CONSTRAINT AFW_01_TYPE_COMNC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_01_TYPE_COMNC ADD (
  CONSTRAINT AFW_01_TYPE_COMNC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_03_CLAS_INTER
  DROP CONSTRAINT AFW_03_CLAS_INTER_PK;

ALTER TABLE APEXFRAMEWORK.AFW_03_CLAS_INTER ADD (
  CONSTRAINT AFW_03_CLAS_INTER_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_03_JOURN_STRUC_APLIC
  DROP CONSTRAINT AFW_03_JOURN_STRUC_APLIC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_03_JOURN_STRUC_APLIC ADD (
  CONSTRAINT AFW_03_JOURN_STRUC_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_03_LIEN_CLAS_INTER_UTILS
  DROP CONSTRAINT AFW_03_LIEN_CLAS_INTER_UTIL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_03_LIEN_CLAS_INTER_UTILS ADD (
  CONSTRAINT AFW_03_LIEN_CLAS_INTER_UTIL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_03_TRACE_EXECT
  DROP CONSTRAINT AFW_03_TRACE_EXECT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_03_TRACE_EXECT ADD (
  CONSTRAINT AFW_03_TRACE_EXECT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_04_CONTX
  DROP CONSTRAINT AFW_04_CONTX_PK;

ALTER TABLE APEXFRAMEWORK.AFW_04_CONTX ADD (
  CONSTRAINT AFW_04_CONTX_PK
  PRIMARY KEY
  (REF_FIL_ARIAN)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_04_CONTX_ETEND
  DROP CONSTRAINT AFW_04_CONTX_ETEND_PK;

ALTER TABLE APEXFRAMEWORK.AFW_04_CONTX_ETEND ADD (
  CONSTRAINT AFW_04_CONTX_ETEND_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_04_FIL_ARIAN
  DROP CONSTRAINT AFW_04_FIL_ARIAN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_04_FIL_ARIAN ADD (
  CONSTRAINT AFW_04_FIL_ARIAN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_04_NAVGT_HISTR
  DROP CONSTRAINT AFW_04_NAVGT_HISTR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_04_NAVGT_HISTR ADD (
  CONSTRAINT AFW_04_NAVGT_HISTR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_04_TUTRL
  DROP CONSTRAINT AFW_04_TUTRL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_04_TUTRL ADD (
  CONSTRAINT AFW_04_TUTRL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_07_AUDIT_STRUC_APLIC
  DROP CONSTRAINT AFW_07_AUDIT_STRUC_APLIC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_07_AUDIT_STRUC_APLIC ADD (
  CONSTRAINT AFW_07_AUDIT_STRUC_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_07_ETAT_SESN
  DROP CONSTRAINT AFW_07_ETAT_SESN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_07_ETAT_SESN ADD (
  CONSTRAINT AFW_07_ETAT_SESN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_07_INSTA_SEMPH
  DROP CONSTRAINT AFW_07_INSTA_SEMPH_PK;

ALTER TABLE APEXFRAMEWORK.AFW_07_INSTA_SEMPH ADD (
  CONSTRAINT AFW_07_INSTA_SEMPH_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_07_SEMPH
  DROP CONSTRAINT AFW_07_SEMPH_PK;

ALTER TABLE APEXFRAMEWORK.AFW_07_SEMPH ADD (
  CONSTRAINT AFW_07_SEMPH_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_07_VALR_AUDIT_STRUC_APLIC
  DROP CONSTRAINT AFW_07_VALR_AUDIT_SA_PK;

ALTER TABLE APEXFRAMEWORK.AFW_07_VALR_AUDIT_STRUC_APLIC ADD (
  CONSTRAINT AFW_07_VALR_AUDIT_SA_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_11_APLIC
  DROP CONSTRAINT AFW_11_APLIC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_11_APLIC ADD (
  CONSTRAINT AFW_11_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_11_ATRIB_ENTIT
  DROP CONSTRAINT AFW_11_ATRIB_ENTIT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_11_ATRIB_ENTIT ADD (
  CONSTRAINT AFW_11_ATRIB_ENTIT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_11_ENTIT
  DROP CONSTRAINT AFW_11_ENTIT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_11_ENTIT ADD (
  CONSTRAINT AFW_11_ENTIT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_11_PARMT_AFW
  DROP CONSTRAINT AFW_11_PARMT_AFW_PK;

ALTER TABLE APEXFRAMEWORK.AFW_11_PARMT_AFW ADD (
  CONSTRAINT AFW_11_PARMT_AFW_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_11_PLUGN
  DROP CONSTRAINT AFW_11_PLUGN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_11_PLUGN ADD (
  CONSTRAINT AFW_11_PLUGN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_11_PRODT
  DROP CONSTRAINT AFW_11_PRODT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_11_PRODT ADD (
  CONSTRAINT AFW_11_PRODT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_11_PRODT_LANG
  DROP CONSTRAINT AFW_11_PRODT_LANG_PK;

ALTER TABLE APEXFRAMEWORK.AFW_11_PRODT_LANG ADD (
  CONSTRAINT AFW_11_PRODT_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_11_PRODT_RESRC
  DROP CONSTRAINT AFW_11_PRODT_RESRC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_11_PRODT_RESRC ADD (
  CONSTRAINT AFW_11_PRODT_RESRC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_11_UTILS
  DROP CONSTRAINT AFW_11_UTILS_PK;

ALTER TABLE APEXFRAMEWORK.AFW_11_UTILS ADD (
  CONSTRAINT AFW_11_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_11_VERSN
  DROP CONSTRAINT AFW_11_VERSN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_11_VERSN ADD (
  CONSTRAINT AFW_11_VERSN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_ACTIO_AUDIT
  DROP CONSTRAINT AFW_12_ACTIO_AUDIT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_ACTIO_AUDIT ADD (
  CONSTRAINT AFW_12_ACTIO_AUDIT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_ARBRE
  DROP CONSTRAINT AFW_12_ARBRE_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_ARBRE ADD (
  CONSTRAINT AFW_12_ARBRE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_ARBRE_NOEUD
  DROP CONSTRAINT AFW_12_ARBRE_NOEUD_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_ARBRE_NOEUD ADD (
  CONSTRAINT AFW_12_ARBRE_NOEUD_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_ATRIB_STRUC_APLIC
  DROP CONSTRAINT AFW_12_ATRIB_STRUC_APLIC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_ATRIB_STRUC_APLIC ADD (
  CONSTRAINT AFW_12_ATRIB_STRUC_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_DEFNT_ACCES
  DROP CONSTRAINT AFW_12_DEFNT_ACCES_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_DEFNT_ACCES ADD (
  CONSTRAINT AFW_12_DEFNT_ACCES_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_DOMN
  DROP CONSTRAINT AFW_12_DOMN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_DOMN ADD (
  CONSTRAINT AFW_12_DOMN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_DOMN_FONCT
  DROP CONSTRAINT AFW_12_DOMN_FONCT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_DOMN_FONCT ADD (
  CONSTRAINT AFW_12_DOMN_FONCT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_DOMN_SERVR_LDAP
  DROP CONSTRAINT AFW_12_DOMN_SERVR_LDAP_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_DOMN_SERVR_LDAP ADD (
  CONSTRAINT AFW_12_DOMN_SERVR_LDAP_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_DOMN_UTILS
  DROP CONSTRAINT AFW_12_DOMN_UTILS_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_DOMN_UTILS ADD (
  CONSTRAINT AFW_12_DOMN_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_EVOLT_STAT
  DROP CONSTRAINT AFW_12_EVOLT_STAT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_EVOLT_STAT ADD (
  CONSTRAINT AFW_12_EVOLT_STAT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_FAVR
  DROP CONSTRAINT AFW_12_FAVR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_FAVR ADD (
  CONSTRAINT AFW_12_FAVR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_FONCT
  DROP CONSTRAINT AFW_12_FONCT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_FONCT ADD (
  CONSTRAINT AFW_12_FONCT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_FONCT_STRUC_APLIC
  DROP CONSTRAINT AFW_12_FONCT_STRUC_APLIC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_FONCT_STRUC_APLIC ADD (
  CONSTRAINT AFW_12_FONCT_STRUC_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_GROUP_GADGT_UTILS
  DROP CONSTRAINT AFW_12_GROUP_GADGT_UTILS_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_GROUP_GADGT_UTILS ADD (
  CONSTRAINT AFW_12_GROUP_GADGT_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_GROUP_STAT
  DROP CONSTRAINT AFW_12_GROUP_STAT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_GROUP_STAT ADD (
  CONSTRAINT AFW_12_GROUP_STAT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_GROUP_UTILS
  DROP CONSTRAINT AFW_12_GROUP_UTILS_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_GROUP_UTILS ADD (
  CONSTRAINT AFW_12_GROUP_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_GR_UT_OPERT_OPTIO_DOMN
  DROP CONSTRAINT AFW_12_GR_UT_OPERT_OPTIO_DO_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_GR_UT_OPERT_OPTIO_DOMN ADD (
  CONSTRAINT AFW_12_GR_UT_OPERT_OPTIO_DO_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_HISTR_ACCES
  DROP CONSTRAINT AFW_12_HISTR_ACCES_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_HISTR_ACCES ADD (
  CONSTRAINT AFW_12_HISTR_ACCES_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_HISTR_TUTRL
  DROP CONSTRAINT AFW_12_HISTR_TUTRL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_HISTR_TUTRL ADD (
  CONSTRAINT AFW_12_HISTR_TUTRL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_LIEN_GADGT_UTILS
  DROP CONSTRAINT AFW_12_LIEN_GADGT_UTILS_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_LIEN_GADGT_UTILS ADD (
  CONSTRAINT AFW_12_LIEN_GADGT_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_LIEN_GADGT_UTILS_PARMT
  DROP CONSTRAINT AFW_12_L_GADGT_UTILS_PARMT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_LIEN_GADGT_UTILS_PARMT ADD (
  CONSTRAINT AFW_12_L_GADGT_UTILS_PARMT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_LIEN_GR_GADGT_GR_UTILS
  DROP CONSTRAINT AFW_12_LIEN_GR_GADGT_GR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_LIEN_GR_GADGT_GR_UTILS ADD (
  CONSTRAINT AFW_12_LIEN_GR_GADGT_GR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_LIEN_GROUP_UTILS
  DROP CONSTRAINT AFW_12_LIEN_GROUP_UTILS_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_LIEN_GROUP_UTILS ADD (
  CONSTRAINT AFW_12_LIEN_GROUP_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_LIEN_STRUC
  DROP CONSTRAINT AFW_12_LIEN_STRUC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_LIEN_STRUC ADD (
  CONSTRAINT AFW_12_LIEN_STRUC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_MEMBR_STRUC
  DROP CONSTRAINT AFW_12_MEMBR_STRUC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_MEMBR_STRUC ADD (
  CONSTRAINT AFW_12_MEMBR_STRUC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_REQT_INTER_UTILS
  DROP CONSTRAINT AFW_12_REQT_INTER_UTILS_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_REQT_INTER_UTILS ADD (
  CONSTRAINT AFW_12_REQT_INTER_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_SERVR_LDAP
  DROP CONSTRAINT AFW_12_SERVR_LDAP_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_SERVR_LDAP ADD (
  CONSTRAINT AFW_12_SERVR_LDAP_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_SESN
  DROP CONSTRAINT AFW_12_SESN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_SESN ADD (
  CONSTRAINT AFW_12_SESN_PK
  PRIMARY KEY
  (ID_SESN)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_STAT
  DROP CONSTRAINT AFW_12_STAT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_STAT ADD (
  CONSTRAINT AFW_12_STAT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_STRUC_ADMIN
  DROP CONSTRAINT AFW_12_STRUC_ADMIN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_STRUC_ADMIN ADD (
  CONSTRAINT AFW_12_STRUC_ADMIN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_STRUC_APLIC
  DROP CONSTRAINT AFW_12_STRUC_APLIC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_STRUC_APLIC ADD (
  CONSTRAINT AFW_12_STRUC_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_STRUC_APLIC_DESTN
  DROP CONSTRAINT AFW_12_STRUC_APLIC_DESTN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_STRUC_APLIC_DESTN ADD (
  CONSTRAINT AFW_12_STRUC_APLIC_DESTN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_STRUC_APLIC_LANG
  DROP CONSTRAINT AFW_12_STRUC_APLIC_LANG_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_STRUC_APLIC_LANG ADD (
  CONSTRAINT AFW_12_STRUC_APLIC_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_STRUC_APLIC_SUIVI
  DROP CONSTRAINT AFW_12_STRUC_APLIC_SUIVI_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_STRUC_APLIC_SUIVI ADD (
  CONSTRAINT AFW_12_STRUC_APLIC_SUIVI_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_TUTRL
  DROP CONSTRAINT AFW_12_TUTRL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_TUTRL ADD (
  CONSTRAINT AFW_12_TUTRL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_TYPE_STRUC
  DROP CONSTRAINT AFW_12_TYPE_STRUC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_TYPE_STRUC ADD (
  CONSTRAINT AFW_12_TYPE_STRUC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_UTILS
  DROP CONSTRAINT AFW_12_UTILS_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_UTILS ADD (
  CONSTRAINT AFW_12_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_12_UTILS_AVATR
  DROP CONSTRAINT AFW_12_UTILS_AVATR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_12_UTILS_AVATR ADD (
  CONSTRAINT AFW_12_UTILS_AVATR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_CONDT_EXECT
  DROP CONSTRAINT AFW_13_CONDT_EXECT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_CONDT_EXECT ADD (
  CONSTRAINT AFW_13_CONDT_EXECT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_CONDT_PILTB
  DROP CONSTRAINT AFW_13_CONDT_PILTB_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_CONDT_PILTB ADD (
  CONSTRAINT AFW_13_CONDT_PILTB_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_DOSR_VIRTL
  DROP CONSTRAINT AFW_13_DOSR_VIRTL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_DOSR_VIRTL ADD (
  CONSTRAINT AFW_13_DOSR_VIRTL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_EMPLA_DOSR_VIRTL
  DROP CONSTRAINT AFW_13_EMPLA_DOSR_VIRTL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_EMPLA_DOSR_VIRTL ADD (
  CONSTRAINT AFW_13_EMPLA_DOSR_VIRTL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_ETAPE_TUTRL
  DROP CONSTRAINT AFW_13_ETAPE_TUTRL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_ETAPE_TUTRL ADD (
  CONSTRAINT AFW_13_ETAPE_TUTRL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_EXPOR_APLIC
  DROP CONSTRAINT AFW_13_EXPOR_APLIC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_EXPOR_APLIC ADD (
  CONSTRAINT AFW_13_EXPOR_APLIC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_EXPOR_PAGE
  DROP CONSTRAINT AFW_13_EXPOR_PAGE_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_EXPOR_PAGE ADD (
  CONSTRAINT AFW_13_EXPOR_PAGE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_FORMT_RESRC
  DROP CONSTRAINT AFW_13_FORMT_RESRC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_FORMT_RESRC ADD (
  CONSTRAINT AFW_13_FORMT_RESRC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_INSTA_PREFR
  DROP CONSTRAINT AFW_13_INSTA_PREFR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_INSTA_PREFR ADD (
  CONSTRAINT AFW_13_INSTA_PREFR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_ITEM_MENU
  DROP CONSTRAINT AFW_13_ITEM_MENU_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_ITEM_MENU ADD (
  CONSTRAINT AFW_13_ITEM_MENU_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_LIEN_CONDT_PILTB
  DROP CONSTRAINT AFW_13_LIEN_CONDT_PILTB_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_LIEN_CONDT_PILTB ADD (
  CONSTRAINT AFW_13_LIEN_CONDT_PILTB_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_LISTE_NAVGT
  DROP CONSTRAINT AFW_13_LISTE_NAVGT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_LISTE_NAVGT ADD (
  CONSTRAINT AFW_13_LISTE_NAVGT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_MENU
  DROP CONSTRAINT AFW_13_MENU_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_MENU ADD (
  CONSTRAINT AFW_13_MENU_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_MIME_TYPE
  DROP CONSTRAINT AFW_13_MIME_TYPE_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_MIME_TYPE ADD (
  CONSTRAINT AFW_13_MIME_TYPE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_NAVGT
  DROP CONSTRAINT AFW_13_NAVGT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_NAVGT ADD (
  CONSTRAINT AFW_13_NAVGT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_NAVGT_ELEMN
  DROP CONSTRAINT AFW_13_NAVGT_ELEMN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_NAVGT_ELEMN ADD (
  CONSTRAINT AFW_13_NAVGT_ELEMN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_OCURN_RESRC
  DROP CONSTRAINT AFW_13_OCURN_RESRC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_OCURN_RESRC ADD (
  CONSTRAINT AFW_13_OCURN_RESRC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_OPERT
  DROP CONSTRAINT AFW_13_OPERT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_OPERT ADD (
  CONSTRAINT AFW_13_OPERT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_OPERT_OPTIO
  DROP CONSTRAINT AFW_13_OPERT_OPTIO_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_OPERT_OPTIO ADD (
  CONSTRAINT AFW_13_OPERT_OPTIO_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_PAGE
  DROP CONSTRAINT AFW_13_PAGE_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_PAGE ADD (
  CONSTRAINT AFW_13_PAGE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_PAGE_IR
  DROP CONSTRAINT AFW_13_PAGE_IR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_PAGE_IR ADD (
  CONSTRAINT AFW_13_PAGE_IR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_PAGE_IR_COLN
  DROP CONSTRAINT AFW_13_PAGE_IR_COLN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_PAGE_IR_COLN ADD (
  CONSTRAINT AFW_13_PAGE_IR_COLN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_PAGE_ITEM
  DROP CONSTRAINT AFW_13_PAGE_ITEM_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_PAGE_ITEM ADD (
  CONSTRAINT AFW_13_PAGE_ITEM_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_PAGE_ITEM_LANG
  DROP CONSTRAINT AFW_13_PAGE_ITEM_LANG_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_PAGE_ITEM_LANG ADD (
  CONSTRAINT AFW_13_PAGE_ITEM_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_PAGE_LANG
  DROP CONSTRAINT AFW_13_PAGE_LANG_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_PAGE_LANG ADD (
  CONSTRAINT AFW_13_PAGE_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_PAGE_PREFR_NAVGT
  DROP CONSTRAINT AFW_13_PAGE_PREFR_NAVGT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_PAGE_PREFR_NAVGT ADD (
  CONSTRAINT AFW_13_PAGE_PREFR_NAVGT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_PREFR
  DROP CONSTRAINT AFW_13_PREFR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_PREFR ADD (
  CONSTRAINT AFW_13_PREFR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_REGN_PILTB
  DROP CONSTRAINT AFW_13_REGN_PILTB_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_REGN_PILTB ADD (
  CONSTRAINT AFW_13_REGN_PILTB_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_REGN_PILTB_LANG
  DROP CONSTRAINT AFW_13_REGN_PILTB_LANG_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_REGN_PILTB_LANG ADD (
  CONSTRAINT AFW_13_REGN_PILTB_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_RESRC
  DROP CONSTRAINT AFW_13_RESRC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_RESRC ADD (
  CONSTRAINT AFW_13_RESRC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_TUTRL
  DROP CONSTRAINT AFW_13_TUTRL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_TUTRL ADD (
  CONSTRAINT AFW_13_TUTRL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_13_TYPE_FICHR
  DROP CONSTRAINT AFW_13_TYPE_FICHR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_13_TYPE_FICHR ADD (
  CONSTRAINT AFW_13_TYPE_FICHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_14_DETL_DOMN_VALR
  DROP CONSTRAINT AFW_14_DETL_DOMN_VALR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_14_DETL_DOMN_VALR ADD (
  CONSTRAINT AFW_14_DETL_DOMN_VALR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_14_DOMN_VALR
  DROP CONSTRAINT AFW_14_DOMN_VALR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_14_DOMN_VALR ADD (
  CONSTRAINT AFW_14_DOMN_VALR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_14_FORMT
  DROP CONSTRAINT AFW_14_FORMT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_14_FORMT ADD (
  CONSTRAINT AFW_14_FORMT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_14_TYPE_DOMN_VALR
  DROP CONSTRAINT AFW_14_TYPE_DOMN_VALR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_14_TYPE_DOMN_VALR ADD (
  CONSTRAINT AFW_14_TYPE_DOMN_VALR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_17_ATACH_COURL_ENTRA
  DROP CONSTRAINT AFW_17_ATACH_COURL_ENTRA_PK;

ALTER TABLE APEXFRAMEWORK.AFW_17_ATACH_COURL_ENTRA ADD (
  CONSTRAINT AFW_17_ATACH_COURL_ENTRA_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_17_COMPT_AXIAT
  DROP CONSTRAINT AFW_17_COMPT_AXIAT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_17_COMPT_AXIAT ADD (
  CONSTRAINT AFW_17_COMPT_AXIAT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_17_COMPT_TWILI
  DROP CONSTRAINT AFW_17_COMPT_TWILI_PK;

ALTER TABLE APEXFRAMEWORK.AFW_17_COMPT_TWILI ADD (
  CONSTRAINT AFW_17_COMPT_TWILI_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_17_COURL
  DROP CONSTRAINT AFW_17_COURL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_17_COURL ADD (
  CONSTRAINT AFW_17_COURL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_17_COURL_DESTN
  DROP CONSTRAINT AFW_17_COURL_DESTN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_17_COURL_DESTN ADD (
  CONSTRAINT AFW_17_COURL_DESTN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_17_COURL_ENTRA
  DROP CONSTRAINT AFW_17_COURL_ENTRA_PK;

ALTER TABLE APEXFRAMEWORK.AFW_17_COURL_ENTRA ADD (
  CONSTRAINT AFW_17_COURL_ENTRA_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_17_COURL_PIECE_JOINT
  DROP CONSTRAINT AFW_17_COURL_PIECE_JOINT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_17_COURL_PIECE_JOINT ADD (
  CONSTRAINT AFW_17_COURL_PIECE_JOINT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_17_PIECE_TELCP_AXIAT
  DROP CONSTRAINT AFW_17_PIECE_TELCP_AXIAT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_17_PIECE_TELCP_AXIAT ADD (
  CONSTRAINT AFW_17_PIECE_TELCP_AXIAT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_17_PROFL_COURL
  DROP CONSTRAINT AFW_17_PROFL_COURL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_17_PROFL_COURL ADD (
  CONSTRAINT AFW_17_PROFL_COURL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_17_PROPR_COURL_ENTRA
  DROP CONSTRAINT AFW_17_PROPR_COURL_ENTRA_PK;

ALTER TABLE APEXFRAMEWORK.AFW_17_PROPR_COURL_ENTRA ADD (
  CONSTRAINT AFW_17_PROPR_COURL_ENTRA_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_17_SMS_TWILI
  DROP CONSTRAINT AFW_17_SMS_TWILI_PK;

ALTER TABLE APEXFRAMEWORK.AFW_17_SMS_TWILI ADD (
  CONSTRAINT AFW_17_SMS_TWILI_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_17_SMS_TWILI_ENTRA
  DROP CONSTRAINT AFW_17_SMS_TWILI_ENTRA_PK;

ALTER TABLE APEXFRAMEWORK.AFW_17_SMS_TWILI_ENTRA ADD (
  CONSTRAINT AFW_17_SMS_TWILI_ENTRA_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_17_TELCP_AXIAT
  DROP CONSTRAINT AFW_17_TELCP_AXIAT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_17_TELCP_AXIAT ADD (
  CONSTRAINT AFW_17_TELCP_AXIAT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_19_BOUTN
  DROP CONSTRAINT AFW_19_BOUTN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_19_BOUTN ADD (
  CONSTRAINT AFW_19_BOUTN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_19_CLE
  DROP CONSTRAINT AFW_19_CLE_PK;

ALTER TABLE APEXFRAMEWORK.AFW_19_CLE ADD (
  CONSTRAINT AFW_19_CLE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_19_DISPN_FONCT
  DROP CONSTRAINT AFW_19_DISPN_FONCT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_19_DISPN_FONCT ADD (
  CONSTRAINT AFW_19_DISPN_FONCT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_19_FONCT
  DROP CONSTRAINT AFW_19_FONCT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_19_FONCT ADD (
  CONSTRAINT AFW_19_FONCT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_19_FONCT_LANG
  DROP CONSTRAINT AFW_19_FONCT_LANG_PK;

ALTER TABLE APEXFRAMEWORK.AFW_19_FONCT_LANG ADD (
  CONSTRAINT AFW_19_FONCT_LANG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_19_SPECF_FONCT
  DROP CONSTRAINT AFW_19_SPECF_FONCT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_19_SPECF_FONCT ADD (
  CONSTRAINT AFW_19_SPECF_FONCT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_20_DEPLM
  DROP CONSTRAINT AFW_20_DEPLM_PK;

ALTER TABLE APEXFRAMEWORK.AFW_20_DEPLM ADD (
  CONSTRAINT AFW_20_DEPLM_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_20_DETL_DOCMN
  DROP CONSTRAINT AFW_20_DETL_DOCMN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_20_DETL_DOCMN ADD (
  CONSTRAINT AFW_20_DETL_DOCMN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_20_DOCMN
  DROP CONSTRAINT AFW_20_DOCMN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_20_DOCMN ADD (
  CONSTRAINT AFW_20_DOCMN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_20_MODL
  DROP CONSTRAINT AFW_20_MODL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_20_MODL ADD (
  CONSTRAINT AFW_20_MODL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_20_MODL_EXCEP
  DROP CONSTRAINT AFW_20_MODL_EXCEP_PK;

ALTER TABLE APEXFRAMEWORK.AFW_20_MODL_EXCEP ADD (
  CONSTRAINT AFW_20_MODL_EXCEP_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_20_MODL_PARMT
  DROP CONSTRAINT AFW_20_MODL_PARMT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_20_MODL_PARMT ADD (
  CONSTRAINT AFW_20_MODL_PARMT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_20_SECTN_DOCMN
  DROP CONSTRAINT AFW_20_SECTN_DOCMN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_20_SECTN_DOCMN ADD (
  CONSTRAINT AFW_20_SECTN_DOCMN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_21_PLUGN_ARBRE
  DROP CONSTRAINT AFW_21_PLUGN_ARBRE_PK;

ALTER TABLE APEXFRAMEWORK.AFW_21_PLUGN_ARBRE ADD (
  CONSTRAINT AFW_21_PLUGN_ARBRE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_21_PLUGN_ARBRE_NOEUD
  DROP CONSTRAINT AFW_21_PLUGN_ARBRE_NOEUD_PK;

ALTER TABLE APEXFRAMEWORK.AFW_21_PLUGN_ARBRE_NOEUD ADD (
  CONSTRAINT AFW_21_PLUGN_ARBRE_NOEUD_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_21_PLUGN_CALND
  DROP CONSTRAINT AFW_21_PLUGN_CALND_PK;

ALTER TABLE APEXFRAMEWORK.AFW_21_PLUGN_CALND ADD (
  CONSTRAINT AFW_21_PLUGN_CALND_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_21_PLUGN_CALND_COULR
  DROP CONSTRAINT AFW_21_PLUGN_CALND_COULR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_21_PLUGN_CALND_COULR ADD (
  CONSTRAINT AFW_21_PLUGN_CALND_COULR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_21_PLUGN_CALND_TYPE
  DROP CONSTRAINT AFW_21_PLUGN_CALND_TYPE_PK;

ALTER TABLE APEXFRAMEWORK.AFW_21_PLUGN_CALND_TYPE ADD (
  CONSTRAINT AFW_21_PLUGN_CALND_TYPE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_21_PLUGN_ITEM_MENU
  DROP CONSTRAINT AFW_21_PLUGN_ITEM_MENU_PK;

ALTER TABLE APEXFRAMEWORK.AFW_21_PLUGN_ITEM_MENU ADD (
  CONSTRAINT AFW_21_PLUGN_ITEM_MENU_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_21_PLUGN_MENU
  DROP CONSTRAINT AFW_21_PLUGN_MENU_PK;

ALTER TABLE APEXFRAMEWORK.AFW_21_PLUGN_MENU ADD (
  CONSTRAINT AFW_21_PLUGN_MENU_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_23_APLIC_MODL_RECHR
  DROP CONSTRAINT AFW_23_APLIC_MODL_RECHR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_23_APLIC_MODL_RECHR ADD (
  CONSTRAINT AFW_23_APLIC_MODL_RECHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_23_DETL_APLIC_MODL_RECHR
  DROP CONSTRAINT AFW_23_DETL_APLIC_MODL_REC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_23_DETL_APLIC_MODL_RECHR ADD (
  CONSTRAINT AFW_23_DETL_APLIC_MODL_REC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_23_DETL_RESLT_RECHR
  DROP CONSTRAINT AFW_23_DETL_RESLT_RECHR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_23_DETL_RESLT_RECHR ADD (
  CONSTRAINT AFW_23_DETL_RESLT_RECHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_23_ENONC_RECHR
  DROP CONSTRAINT AFW_23_ENONC_RECHR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_23_ENONC_RECHR ADD (
  CONSTRAINT AFW_23_ENONC_RECHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_23_MODL_RECHR
  DROP CONSTRAINT AFW_23_MODL_RECHR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_23_MODL_RECHR ADD (
  CONSTRAINT AFW_23_MODL_RECHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_23_PATRN_RECHR
  DROP CONSTRAINT AFW_23_PATRN_RECHR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_23_PATRN_RECHR ADD (
  CONSTRAINT AFW_23_PATRN_RECHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_23_RECHR
  DROP CONSTRAINT AFW_23_RECHR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_23_RECHR ADD (
  CONSTRAINT AFW_23_RECHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_23_RESLT_RECHR
  DROP CONSTRAINT AFW_23_RESLT_RECHR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_23_RESLT_RECHR ADD (
  CONSTRAINT AFW_23_RESLT_RECHR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_CHAMP
  DROP CONSTRAINT AFW_25_CHAMP_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_CHAMP ADD (
  CONSTRAINT AFW_25_CHAMP_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_CHAMP_PUBLC_TRAVL
  DROP CONSTRAINT AFW_25_CHAMP_PUBLC_TRAVL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_CHAMP_PUBLC_TRAVL ADD (
  CONSTRAINT AFW_25_CHAMP_PUBLC_TRAVL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_DOMN_TYPE_PUBLC
  DROP CONSTRAINT AFW_25_DOMN_TYPE_PUBLC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_DOMN_TYPE_PUBLC ADD (
  CONSTRAINT AFW_25_DOMN_TYPE_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_ELEMN_CONFG_PUBLC
  DROP CONSTRAINT AFW_25_ELEMN_CONFG_PUBLC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_ELEMN_CONFG_PUBLC ADD (
  CONSTRAINT AFW_25_ELEMN_CONFG_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_ENGIN
  DROP CONSTRAINT AFW_25_ENGIN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_ENGIN ADD (
  CONSTRAINT AFW_25_ENGIN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_ENGIN_VERSN_PUBLC
  DROP CONSTRAINT AFW_25_ENGIN_VERSN_PUBLC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_ENGIN_VERSN_PUBLC ADD (
  CONSTRAINT AFW_25_ENGIN_VERSN_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_GROUP_PUBLC
  DROP CONSTRAINT AFW_25_GROUP_PUBLC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_GROUP_PUBLC ADD (
  CONSTRAINT AFW_25_GROUP_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_JOURN_TRAVL_EXECT
  DROP CONSTRAINT AFW_25_JOURN_TRAVL_EXECT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_JOURN_TRAVL_EXECT ADD (
  CONSTRAINT AFW_25_JOURN_TRAVL_EXECT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_OCURN_PARMT_PUBLC_TRAVL
  DROP CONSTRAINT AFW_25_OCURN_PARMT_PUB_TRA_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_OCURN_PARMT_PUBLC_TRAVL ADD (
  CONSTRAINT AFW_25_OCURN_PARMT_PUB_TRA_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_PARMT_PUBLC_TRAVL
  DROP CONSTRAINT AFW_25_PARMT_PUBLC_TRAVL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_PARMT_PUBLC_TRAVL ADD (
  CONSTRAINT AFW_25_PARMT_PUBLC_TRAVL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_PARMT_PUBLC_TRAVL_EXECT
  DROP CONSTRAINT AFW_25_PARMT_PUBLC_TRAVL_E_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_PARMT_PUBLC_TRAVL_EXECT ADD (
  CONSTRAINT AFW_25_PARMT_PUBLC_TRAVL_E_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_PARMT_TYPE_PUBLC
  DROP CONSTRAINT AFW_25_PARMT_TYPE_PUBLC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_PARMT_TYPE_PUBLC ADD (
  CONSTRAINT AFW_25_PARMT_TYPE_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_PUBLC
  DROP CONSTRAINT AFW_25_PUBLC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_PUBLC ADD (
  CONSTRAINT AFW_25_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_PUBLC_TRAVL
  DROP CONSTRAINT AFW_25_PUBLC_TRAVL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_PUBLC_TRAVL ADD (
  CONSTRAINT AFW_25_PUBLC_TRAVL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_THEME
  DROP CONSTRAINT AFW_25_THEME_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_THEME ADD (
  CONSTRAINT AFW_25_THEME_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_THEME_SUBST
  DROP CONSTRAINT AFW_25_THEME_SUBST_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_THEME_SUBST ADD (
  CONSTRAINT AFW_25_THEME_SUBST_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_TRAVL
  DROP CONSTRAINT AFW_25_TRAVL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_TRAVL ADD (
  CONSTRAINT AFW_25_TRAVL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_TYPE_PUBLC
  DROP CONSTRAINT AFW_25_TYPE_PUBLC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_TYPE_PUBLC ADD (
  CONSTRAINT AFW_25_TYPE_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_TYPE_TRAVL
  DROP CONSTRAINT AFW_25_TYPE_TRAVL_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_TYPE_TRAVL ADD (
  CONSTRAINT AFW_25_TYPE_TRAVL_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_VALR_CHAMP
  DROP CONSTRAINT AFW_25_VALR_CHAMP_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_VALR_CHAMP ADD (
  CONSTRAINT AFW_25_VALR_CHAMP_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_VALR_ELEMN_CONFG
  DROP CONSTRAINT AFW_25_VALR_ELEMN_CONFG_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_VALR_ELEMN_CONFG ADD (
  CONSTRAINT AFW_25_VALR_ELEMN_CONFG_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_VERSN_PUBLC
  DROP CONSTRAINT AFW_25_VERSN_PUBLC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_VERSN_PUBLC ADD (
  CONSTRAINT AFW_25_VERSN_PUBLC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_25_VERSN_PUBLC_SUBST
  DROP CONSTRAINT AFW_25_VERSN_PUBLC_SUBST_PK;

ALTER TABLE APEXFRAMEWORK.AFW_25_VERSN_PUBLC_SUBST ADD (
  CONSTRAINT AFW_25_VERSN_PUBLC_SUBST_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_29_CONTR
  DROP CONSTRAINT AFW_29_CONTR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_29_CONTR ADD (
  CONSTRAINT AFW_29_CONTR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_30_AFECT_ITEM
  DROP CONSTRAINT AFW_30_AFECT_ITEM_PK;

ALTER TABLE APEXFRAMEWORK.AFW_30_AFECT_ITEM ADD (
  CONSTRAINT AFW_30_AFECT_ITEM_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_30_CARNT_APLIC
  DROP CONSTRAINT AFW_30_CARNT_PRODT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_30_CARNT_APLIC ADD (
  CONSTRAINT AFW_30_CARNT_PRODT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_30_CARNT_PRODT
  DROP CONSTRAINT AFW_30_CARNT_SYSTM_PK;

ALTER TABLE APEXFRAMEWORK.AFW_30_CARNT_PRODT ADD (
  CONSTRAINT AFW_30_CARNT_SYSTM_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_30_CARNT_SPRIN
  DROP CONSTRAINT AFW_30_CARNT_SPRIN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_30_CARNT_SPRIN ADD (
  CONSTRAINT AFW_30_CARNT_SPRIN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_30_CAS_UTILS
  DROP CONSTRAINT AFW_30_CAS_UTILS_PK;

ALTER TABLE APEXFRAMEWORK.AFW_30_CAS_UTILS ADD (
  CONSTRAINT AFW_30_CAS_UTILS_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_30_EFORT_ITEM
  DROP CONSTRAINT AFW_30_EFORT_ITEM_PK;

ALTER TABLE APEXFRAMEWORK.AFW_30_EFORT_ITEM ADD (
  CONSTRAINT AFW_30_EFORT_ITEM_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_30_HISTR_EFORT_RESTN
  DROP CONSTRAINT AFW_30_HISTR_EFORT_RESTN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_30_HISTR_EFORT_RESTN ADD (
  CONSTRAINT AFW_30_HISTR_EFORT_RESTN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_30_ITEM_CARNT_PRODT
  DROP CONSTRAINT AFW_30_ITEM_CARNT_PRODT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_30_ITEM_CARNT_PRODT ADD (
  CONSTRAINT AFW_30_ITEM_CARNT_PRODT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_30_ITEM_CARNT_SPRIN
  DROP CONSTRAINT AFW_30_ITEM_CARNT_SPRIN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_30_ITEM_CARNT_SPRIN ADD (
  CONSTRAINT AFW_30_ITEM_CARNT_SPRIN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_30_PAGE
  DROP CONSTRAINT AFW_30_PAGE_PK;

ALTER TABLE APEXFRAMEWORK.AFW_30_PAGE ADD (
  CONSTRAINT AFW_30_PAGE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_30_PAGE_ITEM
  DROP CONSTRAINT AFW_30_PAGE_ITEM_PK;

ALTER TABLE APEXFRAMEWORK.AFW_30_PAGE_ITEM ADD (
  CONSTRAINT AFW_30_PAGE_ITEM_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_36_ATRIB_DISPN
  DROP CONSTRAINT AFW_36_ATRIB_DISPN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_36_ATRIB_DISPN ADD (
  CONSTRAINT AFW_36_ATRIB_DISPN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_36_FILTR_SESN
  DROP CONSTRAINT AFW_36_FILTR_SESN_PK;

ALTER TABLE APEXFRAMEWORK.AFW_36_FILTR_SESN ADD (
  CONSTRAINT AFW_36_FILTR_SESN_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_36_LIEN_OPERT_FILTR
  DROP CONSTRAINT AFW_36_LIEN_OPERT_FILTR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_36_LIEN_OPERT_FILTR ADD (
  CONSTRAINT AFW_36_LIEN_OPERT_FILTR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_36_OPERT_FILTR
  DROP CONSTRAINT AFW_36_OPERT_FILTR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_36_OPERT_FILTR ADD (
  CONSTRAINT AFW_36_OPERT_FILTR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_36_TYPE_DON
  DROP CONSTRAINT AFW_36_TYPE_DON_PK;

ALTER TABLE APEXFRAMEWORK.AFW_36_TYPE_DON ADD (
  CONSTRAINT AFW_36_TYPE_DON_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_36_VUE
  DROP CONSTRAINT AFW_36_VUE_PK;

ALTER TABLE APEXFRAMEWORK.AFW_36_VUE ADD (
  CONSTRAINT AFW_36_VUE_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_36_VUE_ATRIB
  DROP CONSTRAINT AFW_36_VUE_ATRIB_PK;

ALTER TABLE APEXFRAMEWORK.AFW_36_VUE_ATRIB ADD (
  CONSTRAINT AFW_36_VUE_ATRIB_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_36_VUE_TRI_SECND
  DROP CONSTRAINT AFW_36_VUE_TRI_SECND_PK;

ALTER TABLE APEXFRAMEWORK.AFW_36_VUE_TRI_SECND ADD (
  CONSTRAINT AFW_36_VUE_TRI_SECND_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_37_GADGT
  DROP CONSTRAINT AFW_37_GADGT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_37_GADGT ADD (
  CONSTRAINT AFW_37_GADGT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_37_GADGT_CATGR
  DROP CONSTRAINT AFW_37_GADGT_CATGR_PK;

ALTER TABLE APEXFRAMEWORK.AFW_37_GADGT_CATGR ADD (
  CONSTRAINT AFW_37_GADGT_CATGR_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_37_GADGT_PARMT
  DROP CONSTRAINT AFW_37_GADGT_PARMT_PK;

ALTER TABLE APEXFRAMEWORK.AFW_37_GADGT_PARMT ADD (
  CONSTRAINT AFW_37_GADGT_PARMT_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_37_GADGT_PARMT_RACRC
  DROP CONSTRAINT AFW_37_GADGT_PARMT_RACRC_PK;

ALTER TABLE APEXFRAMEWORK.AFW_37_GADGT_PARMT_RACRC ADD (
  CONSTRAINT AFW_37_GADGT_PARMT_RACRC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_37_LIEN_GADGT_PARMT_RACRC
  DROP CONSTRAINT AFW_37_LIEN_GADGT_PARMT_R_PK;

ALTER TABLE APEXFRAMEWORK.AFW_37_LIEN_GADGT_PARMT_RACRC ADD (
  CONSTRAINT AFW_37_LIEN_GADGT_PARMT_R_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.AFW_37_TABL_BORD
  DROP CONSTRAINT AFW_37_TABL_BORD_PK;

ALTER TABLE APEXFRAMEWORK.AFW_37_TABL_BORD ADD (
  CONSTRAINT AFW_37_TABL_BORD_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);


ALTER TABLE APEXFRAMEWORK.TC_AFW_07_SEQNC
  DROP CONSTRAINT TC_AFW_07_SEQNC_PK;

ALTER TABLE APEXFRAMEWORK.TC_AFW_07_SEQNC ADD (
  CONSTRAINT TC_AFW_07_SEQNC_PK
  PRIMARY KEY
  (SEQNC)
  ENABLE VALIDATE);
