SET DEFINE OFF;
CREATE TABLE AFW_12_INSTA_SCENR_NOTFC
(
  SEQNC                  NUMBER(10),
  REF_DOMN               NUMBER(10),
  REF_ATRIB_SCENR_NOTFC  NUMBER(10),
  UTILS_CREAT            VARCHAR2(123 BYTE),
  DATE_CREAT             DATE,
  UTILS_MODFC            VARCHAR2(123 BYTE),
  DATE_MODFC             DATE,
  REF_SCENR_NOTFC_ACTIO  NUMBER(10),
  INDIC_NOTFR            VARCHAR2(1 BYTE)       DEFAULT 'N'
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
