SET DEFINE OFF;
CREATE TABLE AFW_21_PLUGN_CALND_TYPE
(
  SEQNC             NUMBER(10),
  CODE              VARCHAR2(23 BYTE),
  NOM               VARCHAR2(60 BYTE),
  DESCR             VARCHAR2(2000 BYTE),
  DATE_CREAT        DATE,
  UTILS_CREAT       VARCHAR2(123 BYTE),
  DATE_MODFC        DATE,
  UTILS_MODFC       VARCHAR2(123 BYTE),
  COULR_TEXTE       VARCHAR2(7 BYTE),
  COULR_BORDR       VARCHAR2(7 BYTE),
  COULR_ARIER_PLAN  VARCHAR2(7 BYTE),
  REF_DOMN          NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
