SET DEFINE OFF;
CREATE TABLE AFW_12_DOMN_FONCT
(
  SEQNC         NUMBER(10),
  REF_FONCT     NUMBER(10),
  REF_DOMN      NUMBER(10),
  INDIC_ACTIF   VARCHAR2(1 BYTE)                DEFAULT 'O',
  DATE_CREAT    DATE,
  UTILS_CREAT   VARCHAR2(123 BYTE),
  DATE_MODFC    DATE,
  UTILS_MODFC   VARCHAR2(123 BYTE),
  DNR_REF_DOMN  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
