SET DEFINE OFF;
CREATE TABLE AFW_07_INSTA_SEMPH
(
  SEQNC        NUMBER(10),
  REF_SEMPH    NUMBER(10),
  ID_SESN      NUMBER,
  DATE_CREAT   DATE,
  UTILS_CREAT  VARCHAR2(123 BYTE),
  INDIC_SEQNC  VARCHAR2(1 BYTE),
  PAGE_PERST   VARCHAR2(500 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
