SET DEFINE OFF;
CREATE TABLE AFW_36_LIEN_OPERT_FILTR
(
  SEQNC            NUMBER(10),
  REF_TYPE_DON     NUMBER(10),
  REF_OPERT_FILTR  NUMBER(10),
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_CREAT       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  INDIC_DEFT       VARCHAR2(1 BYTE)             DEFAULT 'N'
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
