SET DEFINE OFF;
CREATE TABLE AFW_11_PRODT
(
  SEQNC                         NUMBER(10),
  CODE                          VARCHAR2(30 BYTE),
  NOM                           VARCHAR2(60 BYTE),
  DATE_CREAT                    DATE,
  UTILS_CREAT                   VARCHAR2(123 BYTE),
  DATE_MODFC                    DATE,
  UTILS_MODFC                   VARCHAR2(123 BYTE),
  PROCD_EXPOR_METDN             VARCHAR2(100 BYTE),
  TAIL_TABL_EXTRA               NUMBER(10)      DEFAULT 10,
  INDIC_EXTRA_TOUT              VARCHAR2(1 BYTE) DEFAULT 'N',
  REF_GROUP_UTILS_ADMIN         NUMBER(10),
  DOSR_FICHR                    VARCHAR2(200 BYTE),
  IDENT_ENVIR                   VARCHAR2(60 BYTE),
  REF_VERSN                     NUMBER(10),
  MESG_TOUT_DROIT_RESRV         VARCHAR2(150 BYTE),
  JQUER_UI_CSS_SCOPE            VARCHAR2(50 BYTE),
  INDIC_AFICH_ERR_CODE          VARCHAR2(1 BYTE) DEFAULT 'O',
  REF_MESG_SUCS                 NUMBER(10),
  REF_MESG_ECHEC                NUMBER(10),
  REF_MESG_FETCH                NUMBER(10),
  REF_MESG_RANGE_SUPRM          NUMBER(10),
  REF_MESG_RANGE_MODF           NUMBER(10),
  REF_MESG_RANGE_INSER          NUMBER(10),
  REF_MESG_AUCUN_DON_TROUV      NUMBER(10),
  REF_MESG_TROP_DON_TROUV       NUMBER(10),
  REF_MESG_AUDIT_CREAT          NUMBER(10),
  REF_MESG_AUDIT_MODFC          NUMBER(10),
  REF_MESG_AUDIT_SUPRS          NUMBER(10),
  FONCT_OBTEN_BASE_URL          VARCHAR2(92 BYTE),
  REF_APLIC_ACUEI               NUMBER(10),
  REF_PAGE_ACUEI                NUMBER(10),
  REF_APLIC_COMNT_BOGUE         NUMBER(10),
  REF_PAGE_COMNT_BOGUE          NUMBER(10),
  INDIC_PAGE_INEXS_MAJ_REFRN    VARCHAR2(1 BYTE) DEFAULT 'N',
  PROCD_IMPRE_ENTET_PDF_IR      VARCHAR2(200 BYTE),
  PROCD_IMPRE_PIED_PAGE_PDF_IR  VARCHAR2(200 BYTE),
  PROCD_PLPDF_COULR             VARCHAR2(200 BYTE),
  COMPT_GENRL                   NUMBER(6)       DEFAULT 0,
  DOMN_DOCMN_HTML               VARCHAR2(100 BYTE),
  INITL_COMPS_JAVSC             VARCHAR2(4000 BYTE),
  NOTE_SCRIP_PRE_MIGRT          VARCHAR2(4000 BYTE),
  NOTE_SCRIP_POST_MIGRT         VARCHAR2(4000 BYTE),
  PROCD_INITL_SESN              VARCHAR2(4000 BYTE),
  FONCT_MIGRT_PERSN             VARCHAR2(92 BYTE),
  INDIC_SYSTM                   VARCHAR2(1 BYTE) DEFAULT 'N'
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
