SET DEFINE OFF;
CREATE TABLE AFW_13_PAGE
(
  SEQNC                          NUMBER(10),
  NUMR_APEX                      NUMBER,
  NOM                            VARCHAR2(255 BYTE),
  DESCR                          VARCHAR2(400 BYTE),
  DATE_CREAT                     DATE,
  UTILS_CREAT                    VARCHAR2(123 BYTE),
  DATE_MODFC                     DATE,
  UTILS_MODFC                    VARCHAR2(123 BYTE),
  REF_STRUC_APLIC                NUMBER(10),
  INDIC_PRISE_CHARG_AFW01        VARCHAR2(1 BYTE) DEFAULT 'O',
  INDIC_PRISE_CHARG_AFW04        VARCHAR2(1 BYTE) DEFAULT 'O',
  REF_MESG_SUPRS_SPECF           NUMBER(10),
  INDIC_PRISE_CHARG_AFW19        VARCHAR2(1 BYTE) DEFAULT 'O',
  INDIC_PRISE_CHARG_AFW13_NAVGT  VARCHAR2(1 BYTE) DEFAULT 'O',
  INDIC_PRISE_CHARG_AFW18        VARCHAR2(1 BYTE) DEFAULT 'N',
  REF_PAGE_RECHR                 NUMBER(10),
  INDIC_PRISE_CHARG_AFW14_POPUP  VARCHAR2(1 BYTE) DEFAULT 'N',
  INDIC_PRISE_CHARG_AFW13_CONFR  VARCHAR2(1 BYTE) DEFAULT 'N',
  PREFX_MESG                     VARCHAR2(3 BYTE),
  DATE_DERNR_MAJ_REFRN_APEX      DATE,
  REF_MESG_SUCS_SPECF            NUMBER(10),
  REF_MESG_ECHEC_SPECF           NUMBER(10),
  REF_MESG_FETCH_SPECF           NUMBER(10),
  REF_MESG_RANGE_SUPRM_SPECF     NUMBER(10),
  REF_MESG_RANGE_MODF_SPECF      NUMBER(10),
  REF_MESG_RANGE_INSER_SPECF     NUMBER(10),
  REF_MESG_AUCUN_DON_TROUV       NUMBER(10),
  REF_MESG_TROP_DON_TROUV        NUMBER(10),
  REF_APLIC                      NUMBER(10),
  DNR_REF_APLIC                  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
