SET DEFINE OFF;
CREATE TABLE AFW_11_PARMT_AFW
(
  SEQNC        NUMBER(10),
  CODE         VARCHAR2(30 BYTE),
  VALR         VARCHAR2(200 BYTE),
  DATE_CREAT   DATE,
  UTILS_CREAT  VARCHAR2(123 BYTE),
  DATE_MODFC   DATE,
  UTILS_MODFC  VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
