SET DEFINE OFF;
CREATE TABLE AFW_25_PUBLC_TRAVL
(
  SEQNC              NUMBER(10),
  REF_PUBLC          NUMBER(10),
  REF_TRAVL          NUMBER(10),
  DATE_CREAT         DATE,
  UTILS_CREAT        VARCHAR2(123 BYTE),
  DATE_MODFC         DATE,
  UTILS_MODFC        VARCHAR2(123 BYTE),
  REF_STAT           NUMBER(10),
  NOM                VARCHAR2(200 BYTE),
  INDIC_PARMT_ALIMN  VARCHAR2(1 BYTE)           DEFAULT 'N',
  REF_VERSN_PUBLC    NUMBER(10),
  RESLT_HTML         CLOB
)
LOB (RESLT_HTML) STORE AS BASICFILE (
  TABLESPACE  APEXFRAMEWORK
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
