SET DEFINE OFF;
CREATE TABLE AFW_30_ITEM_CARNT_SPRIN
(
  SEQNC                 NUMBER(10),
  NOM                   VARCHAR2(200 BYTE),
  DESCR                 VARCHAR2(4000 BYTE),
  NUMR_REFRC_DOCMN      NUMBER(3),
  REF_ITEM_CARNT_PRODT  NUMBER(10),
  REF_CARNT_SPRIN       NUMBER(10),
  EFORT_PREVU           NUMBER(10,2),
  EFORT_RESTN           NUMBER(10,2),
  REF_DV_PRIOR          NUMBER(10),
  DATE_CREAT            DATE,
  UTILS_CREAT           VARCHAR2(123 BYTE),
  DATE_MODFC            DATE,
  UTILS_MODFC           VARCHAR2(123 BYTE),
  REF_AFW_30_PAGE       NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
