SET DEFINE OFF;
CREATE TABLE AFW_01_RESLT_DESTN
(
  SEQNC                  NUMBER(10),
  REF_DESTN              NUMBER(10),
  DNR_REF_PRODT          NUMBER(10),
  IDENT_ACCES            VARCHAR2(4000 BYTE),
  IDENT_ACCES_FORMT      VARCHAR2(4000 BYTE),
  UTILS_CREAT            VARCHAR2(123 BYTE),
  DATE_CREAT             DATE,
  UTILS_MODFC            VARCHAR2(123 BYTE),
  DATE_MODFC             DATE,
  NOM                    VARCHAR2(60 BYTE),
  REF_STRUC_APLIC_ACCES  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
