SET DEFINE OFF;
CREATE TABLE AFW_11_VERSN
(
  SEQNC             NUMBER(10),
  NUMR_VERSN_1      NUMBER(2),
  NUMR_VERSN_2      NUMBER(2),
  NUMR_VERSN_3      NUMBER(2),
  NUMR_VERSN_4      NUMBER(2),
  DATE_CREAT        DATE,
  UTILS_CREAT       VARCHAR2(123 BYTE),
  DATE_MODFC        DATE,
  UTILS_MODFC       VARCHAR2(123 BYTE),
  REF_PRODT         NUMBER(10),
  INDIC_DOCMN_VERL  VARCHAR2(1 BYTE)            DEFAULT 'O',
  NOM               VARCHAR2(30 BYTE),
  REF_PLUGN         NUMBER(10),
  CODE              VARCHAR2(23 BYTE),
  DNR_REF_PRODT     NUMBER(10),
  REF_APLIC         NUMBER(10),
  DNR_REF_APLIC     NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
