SET DEFINE OFF;
CREATE TABLE AFW_17_SMS_TWILI
(
  SEQNC            NUMBER(10),
  NUMR_DE          NUMBER(18),
  NUMR_A           NUMBER(18),
  MESG             VARCHAR2(160 CHAR),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE),
  TW_SID           VARCHAR2(100 BYTE),
  TW_STATUS        VARCHAR2(50 BYTE),
  TW_PRICE         NUMBER(5,2),
  TW_URI           VARCHAR2(500 BYTE),
  STAT_SOUMS       VARCHAR2(30 BYTE),
  DATE_ENVOI_DIFR  DATE,
  REF_COMPT_TWILI  NUMBER(10),
  NUMR_MESG        NUMBER(3),
  NOMBR_MESG_TOTL  NUMBER(3),
  REF_MESG_PRECD   NUMBER(10),
  ID_SESN          NUMBER,
  GROUP_SMS        NUMBER(10),
  REPNS_SERVR      SYS.XMLTYPE,
  SENS             VARCHAR2(5 BYTE)
)
XMLTYPE REPNS_SERVR STORE AS SECUREFILE BINARY XML (
  TABLESPACE  APEXFRAMEWORK
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          104K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
ALLOW NONSCHEMA
DISALLOW ANYSCHEMA
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
