SET DEFINE OFF;
CREATE TABLE AFW_01_DESTN_CONFG_EVENM_NOTFB
(
  SEQNC                     NUMBER(10),
  REF_DV_NATR_DESTN         NUMBER(10),
  REF_CONFG_EVENM_NOTFB     NUMBER(10),
  REF_DESTN                 NUMBER(10),
  UTILS_CREAT               VARCHAR2(123 BYTE),
  DATE_MODFC                DATE,
  UTILS_MODFC               VARCHAR2(123 BYTE),
  DATE_CREAT                DATE,
  REF_RESLT_DESTN           NUMBER(10),
  REF_ATRIB_SA_NOM_FORMT    NUMBER(10),
  REF_ATRIB_SA_ADRES_DESTN  NUMBER(10),
  DNR_REF_DOMN              NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
