SET DEFINE OFF;
CREATE TABLE AFW_25_OCURN_PARMT_PUBLC_TRAVL
(
  SEQNC                  NUMBER(10),
  VALR_DATE              DATE,
  VALR_NUMBR             NUMBER,
  VALR_VARCH             VARCHAR2(4000 BYTE),
  REF_PARMT_PUBLC_TRAVL  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
