SET DEFINE OFF;
CREATE TABLE AFW_13_LIEN_CONDT_PILTB
(
  SEQNC             NUMBER(10),
  REF_PAGE_ITEM     NUMBER(10),
  REF_CONDT_PILTB   NUMBER(10),
  INDIC_LECTR_SEUL  VARCHAR2(1 BYTE),
  DATE_CREAT        DATE,
  UTILS_CREAT       VARCHAR2(123 BYTE),
  DATE_MODFC        DATE,
  UTILS_MODFC       VARCHAR2(123 BYTE),
  INDIC_AFICH       VARCHAR2(1 BYTE)            DEFAULT 'O',
  DNR_REF_APLIC     NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
