SET DEFINE OFF;
CREATE TABLE AFW_13_NAVGT_ELEMN
(
  SEQNC        NUMBER(10),
  NUMR_ELEMN   NUMBER(8),
  INDIC_COURN  VARCHAR2(1 BYTE),
  SEQNC_ELEMN  NUMBER(10),
  REF_NAVGT    NUMBER(10),
  DATE_CREAT   DATE,
  UTILS_CREAT  VARCHAR2(123 BYTE),
  DATE_MODFC   DATE,
  UTILS_MODFC  VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
