SET DEFINE OFF;
CREATE TABLE AFW_01_MESG_INFOR
(
  SEQNC          NUMBER(10),
  TEXT_MESG      VARCHAR2(4000 BYTE),
  UTILS_CREAT    VARCHAR2(123 BYTE),
  DATE_CREAT     DATE,
  SESS_ID        NUMBER,
  REF_UTILS      NUMBER(10),
  REF_MESG_LANG  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
