SET DEFINE OFF;
CREATE TABLE AFW_25_VERSN_PUBLC_SUBST
(
  SEQNC                  NUMBER(10),
  DNR_REF_PRODT          NUMBER(10),
  REF_VERSN_PUBLC        NUMBER(10),
  REF_VERSN_PUBLC_SUBST  NUMBER,
  NOM                    VARCHAR2(60 BYTE),
  CODE_SUBST             VARCHAR2(50 BYTE),
  VALR_SUBST             VARCHAR2(4000 BYTE),
  UTILS_CREAT            VARCHAR2(123 BYTE),
  DATE_CREAT             DATE,
  UTILS_MODFC            VARCHAR2(123 BYTE),
  DATE_MODFC             DATE,
  TYPE_SUBST             VARCHAR2(23 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
