SET DEFINE OFF;
CREATE TABLE AFW_12_LIEN_ROLE_APROB
(
  SEQNC           NUMBER(10),
  REF_ROLE_APROB  NUMBER(10),
  REF_APROB       NUMBER(10),
  UTILS_CREAT     VARCHAR2(123 BYTE),
  DATE_CREAT      DATE,
  UTILS_MODFC     VARCHAR2(123 BYTE),
  DATE_MODFC      DATE,
  DNR_REF_DOMN    NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
