SET DEFINE OFF;
CREATE TABLE AFW_12_ROLE_APROB
(
  SEQNC           NUMBER(10),
  CODE            VARCHAR2(23 BYTE),
  NOM             VARCHAR2(60 BYTE),
  UTILS_CREAT     VARCHAR2(123 BYTE),
  DATE_CREAT      DATE,
  UTILS_MODFC     VARCHAR2(123 BYTE),
  DATE_MODFC      DATE,
  DNR_REF_DOMN    NUMBER(10),
  REF_GROUP_STAT  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
