SET DEFINE OFF;
CREATE TABLE AFW_29_RESLT_REQUT_AQ
(
  REF_CONTR  NUMBER(10),
  ID         NUMBER,
  FLOW_ID    NUMBER,
  PAGE_ID    NUMBER,
  NOM_COMPS  VARCHAR2(500 BYTE),
  NIV_GRAVT  NUMBER(1),
  NATR       VARCHAR2(500 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
