SET DEFINE OFF;
CREATE TABLE AFW_37_TABL_BORD
(
  SEQNC           NUMBER(10),
  REF_PRODT       NUMBER(10),
  CODE            VARCHAR2(50 BYTE),
  NOM             VARCHAR2(250 BYTE),
  DESCR           VARCHAR2(4000 BYTE),
  DATE_CREAT      DATE,
  UTILS_CREAT     VARCHAR2(123 BYTE),
  DATE_MODFC      DATE,
  UTILS_MODFC     VARCHAR2(123 BYTE),
  DNR_REF_PRODT   NUMBER(10),
  NOM_GROUP_DEFT  VARCHAR2(250 BYTE)            DEFAULT 'Mon Dashboard'
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
