SET DEFINE OFF;
CREATE TABLE AFW_36_FILTR_SESN
(
  SEQNC            NUMBER(10),
  REF_SESN         NUMBER,
  REF_OPERT_FILTR  NUMBER(10),
  REF_ATRIB_DISPN  NUMBER(10),
  REF_PAGE         NUMBER(10),
  DNR_CONDT_SQL    VARCHAR2(4000 BYTE),
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_CREAT       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  DNR_CONDT_AFICH  VARCHAR2(4000 BYTE),
  VALR_VARCH1      VARCHAR2(4000 BYTE),
  VALR_VARCH2      VARCHAR2(4000 BYTE),
  VALR_NUMBR1      NUMBER,
  VALR_NUMBR2      NUMBER,
  VALR_DATE1       DATE,
  VALR_DATE2       DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
