SET DEFINE OFF;
CREATE TABLE AFW_13_PAGE_ITEM
(
  SEQNC              NUMBER(10),
  REF_PAGE           NUMBER(10),
  ID_APEX            NUMBER,
  NOM_APEX           VARCHAR2(500 BYTE),
  DATE_CREAT         DATE,
  UTILS_CREAT        VARCHAR2(123 BYTE),
  DATE_MODFC         DATE,
  UTILS_MODFC        VARCHAR2(123 BYTE),
  LIBL               VARCHAR2(500 BYTE),
  INDIC_CREAT        VARCHAR2(1 BYTE),
  INDIC_MODFC        VARCHAR2(1 BYTE),
  INDIC_SUPRS        VARCHAR2(1 BYTE),
  INDIC_EN_CREAT     VARCHAR2(1 BYTE),
  INDIC_EN_MODFC     VARCHAR2(1 BYTE),
  TYPE_ITEM          VARCHAR2(5 BYTE)           DEFAULT 'ITEM',
  REF_OPERT          NUMBER(10),
  REF_MESG_AIDE      NUMBER(10),
  DEPSM_ALIAS_COLN   VARCHAR2(200 BYTE),
  INDIC_RECHR        VARCHAR2(1 BYTE)           DEFAULT 'N',
  INDIC_CONFR_SAUVG  VARCHAR2(1 BYTE),
  DNR_REF_APLIC      NUMBER(10),
  ICONE_BULLE_AIDE   VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
