SET DEFINE OFF;
CREATE TABLE AFW_13_ETAPE_TUTRL
(
  SEQNC                   NUMBER(10),
  NOM                     VARCHAR2(100 BYTE),
  DESCR                   VARCHAR2(400 BYTE),
  REF_TUTRL               NUMBER(10),
  ORDRE_PRESN             NUMBER(10),
  REF_PAGE_ITEM           NUMBER(10),
  SELCT_JQUER_ELEMN_HTML  VARCHAR2(100 BYTE),
  REF_MESG_TITRE          NUMBER(10),
  REF_MESG_DESCR          NUMBER(10),
  REF_DV_POSTN_AFICH      NUMBER(10),
  INDIC_AFICH_TOILE_FOND  VARCHAR2(1 BYTE)      DEFAULT 'N',
  INDIC_MODE_REFLX        VARCHAR2(1 BYTE)      DEFAULT 'N',
  INDIC_AFICH_ORPHE       VARCHAR2(1 BYTE)      DEFAULT 'N',
  TEMPL_HTML              VARCHAR2(4000 BYTE),
  DATE_CREAT              DATE,
  UTILS_CREAT             VARCHAR2(123 BYTE),
  DATE_MODFC              DATE,
  UTILS_MODFC             VARCHAR2(123 BYTE),
  ON_NEXT                 VARCHAR2(400 BYTE),
  ON_PREV                 VARCHAR2(400 BYTE),
  ON_SHOW                 VARCHAR2(400 BYTE),
  ON_SHOWN                VARCHAR2(400 BYTE),
  ON_HIDE                 VARCHAR2(400 BYTE),
  ON_HIDN                 VARCHAR2(400 BYTE),
  REF_PAGE                NUMBER(10),
  REF_TUTRL_SUIVN         NUMBER(10),
  REF_ETAPE_TUTRL_SUIVN   NUMBER(10),
  DNR_REF_PRODT           NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
