SET DEFINE OFF;
CREATE TABLE AFW_13_ITEM_MENU
(
  SEQNC                          NUMBER(10),
  CODE                           VARCHAR2(23 BYTE),
  NOM                            VARCHAR2(60 BYTE),
  DESCR                          VARCHAR2(2000 BYTE),
  AIDE_INSTA                     VARCHAR2(2000 BYTE),
  TITRE_AIDE_INSTA               VARCHAR2(60 BYTE),
  ORDRE_PRESN                    NUMBER,
  REF_PAGE                       NUMBER(10),
  ICONE                          VARCHAR2(1000 BYTE),
  EFACR_CACHE                    VARCHAR2(1000 BYTE),
  REF_MENU                       NUMBER(10),
  REF_DV_VALR_REQST              NUMBER(10),
  FORML_VALR_REQST               VARCHAR2(4000 BYTE),
  INDIC_REINT_PAGNT              VARCHAR2(1 BYTE) DEFAULT 'N',
  INDIC_REINT_PAGE_IR            VARCHAR2(1 BYTE) DEFAULT 'N',
  INDIC_CLEAR_PAGE_IR            VARCHAR2(1 BYTE) DEFAULT 'N',
  REF_DV_VALR_SCPC               NUMBER(10),
  FORML_VALR_SCPC                VARCHAR2(4000 BYTE),
  REF_DV_VALR_SSPC               NUMBER(10),
  FORML_VALR_SSPC                VARCHAR2(4000 BYTE),
  REF_DV_VALR_SAPC               NUMBER(10),
  FORML_VALR_SAPC                VARCHAR2(4000 BYTE),
  REF_DV_VALR_SCPI               NUMBER(10),
  FORML_VALR_SCPI                VARCHAR2(4000 BYTE),
  REF_DV_VALR_SSPI               NUMBER(10),
  FORML_VALR_SSPI                VARCHAR2(4000 BYTE),
  REF_DV_VALR_SAPI               NUMBER(10),
  FORML_VALR_SAPI                VARCHAR2(4000 BYTE),
  REF_DV_VALR_SNPI               NUMBER(10),
  FORML_VALR_SNPI                VARCHAR2(4000 BYTE),
  DATE_CREAT                     DATE,
  UTILS_CREAT                    VARCHAR2(123 BYTE),
  DATE_MODFC                     DATE,
  UTILS_MODFC                    VARCHAR2(123 BYTE),
  INDIC_SOUMS_PAGE               VARCHAR2(1 BYTE) DEFAULT 'N',
  INDIC_REINT_NAVGT              VARCHAR2(1 BYTE) DEFAULT 'O',
  REF_ITEM_MENU                  NUMBER(10),
  DNR_REF_PRODT                  NUMBER(10),
  REF_STRUC_APLIC                NUMBER(10),
  FORML_LIBL                     VARCHAR2(4000 BYTE),
  LISTE_REF_PAGE_ACTIV           VARCHAR2(1000 BYTE),
  REF_RESRC                      NUMBER(10),
  REF_OCURN_RESRC                NUMBER(10),
  REF_FORMT_RESRC                NUMBER(10),
  REF_DV_VALR_INSTA_LIBL         NUMBER(10),
  REF_DV_VALR_URL                NUMBER(10),
  FORML_VALR_URL                 VARCHAR2(4000 BYTE),
  INDIC_GERER_SIDF               VARCHAR2(1 BYTE) DEFAULT 'N',
  REF_APLIC                      NUMBER(10),
  REF_DV_VALR_INSTA_CONDT_AFICH  NUMBER(10),
  FORML_CONDT_AFICH              VARCHAR2(4000 BYTE),
  LIEN_ID_HTML                   VARCHAR2(100 BYTE),
  LIEN_CLASS_CSS_HTML            VARCHAR2(100 BYTE),
  LIEN_ATRIB_HTML                VARCHAR2(100 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
