SET DEFINE OFF;
CREATE TABLE AFW_20_DEPLM
(
  SEQNC           NUMBER(10),
  NOM             VARCHAR2(60 BYTE),
  DATE_CREAT      DATE,
  UTILS_CREAT     VARCHAR2(123 BYTE),
  DATE_MODFC      DATE,
  UTILS_MODFC     VARCHAR2(123 BYTE),
  REF_MODL        NUMBER(10),
  REF_MODL_PARMT  NUMBER(10),
  REF_PRODT_LANG  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
