SET DEFINE OFF;
CREATE TABLE AFW_11_PRODT_RESRC
(
  SEQNC            NUMBER(10),
  REF_PRODT        NUMBER(10),
  REF_RESRC        NUMBER(10),
  REF_FORMT        NUMBER(10),
  REF_CONDT_EXECT  NUMBER(10),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE),
  REF_PLUGN        NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
