SET DEFINE OFF;
CREATE TABLE AFW_13_OPERT
(
  SEQNC          NUMBER(10),
  NOM            VARCHAR2(100 BYTE),
  DESCR          VARCHAR2(400 BYTE),
  DATE_CREAT     DATE,
  UTILS_CREAT    VARCHAR2(123 BYTE),
  DATE_MODFC     DATE,
  UTILS_MODFC    VARCHAR2(123 BYTE),
  REF_PRODT      NUMBER(10),
  CODE           VARCHAR2(23 BYTE),
  DNR_REF_PRODT  NUMBER(10),
  REF_FONCT      NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
