SET DEFINE OFF;
CREATE TABLE AFW_30_HISTR_EFORT_RESTN
(
  SEQNC                 NUMBER(10),
  REF_ITEM_CARNT_SPRIN  NUMBER(10),
  DATE_HEURE_SAISI      DATE,
  EFORT_RESTN           NUMBER(10,2),
  DATE_CREAT            DATE,
  UTILS_CREAT           VARCHAR2(123 BYTE),
  DATE_MODFC            DATE,
  UTILS_MODFC           VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
