SET DEFINE OFF;
CREATE TABLE AFW_36_OPERT_FILTR
(
  SEQNC                   NUMBER(10),
  CODE                    VARCHAR2(23 BYTE),
  NOM                     VARCHAR2(60 BYTE),
  TEXTE_AFICH             VARCHAR2(4000 BYTE),
  CONDT_SQL               VARCHAR2(4000 BYTE),
  UTILS_CREAT             VARCHAR2(123 BYTE),
  DATE_CREAT              DATE,
  UTILS_MODFC             VARCHAR2(123 BYTE),
  DATE_MODFC              DATE,
  INDIC_VALR2             VARCHAR2(1 BYTE)      DEFAULT 'N',
  INDIC_AUTO_LANCR_RECHR  VARCHAR2(1 BYTE)      DEFAULT 'N'
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
