SET DEFINE OFF;
CREATE TABLE AFW_20_MODL_PARMT
(
  SEQNC            NUMBER(10),
  REF_MODL         NUMBER(10),
  NOM_ORGAN        VARCHAR2(30 BYTE),
  REF_DV_TYPE_DON  NUMBER(10),
  POSTN            NUMBER(3),
  VALR_DEFT        VARCHAR2(200 BYTE),
  SENS             VARCHAR2(15 BYTE),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE),
  INDIC_PUBLC      VARCHAR2(1 BYTE)             DEFAULT 'N',
  INDIC_RETR       VARCHAR2(1 BYTE)             DEFAULT 'N'
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
