SET DEFINE OFF;
CREATE TABLE AFW_07_VALR_AUDIT_STRUC_APLIC
(
  SEQNC                  NUMBER(16),
  REF_AUDIT_STRUC_APLIC  NUMBER(10),
  CODE                   VARCHAR2(30 BYTE),
  VALR_FORMT             VARCHAR2(4000 BYTE),
  DATE_CREAT             DATE,
  UTILS_CREAT            VARCHAR2(123 BYTE),
  DATE_MODFC             DATE,
  UTILS_MODFC            VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
