SET DEFINE OFF;
CREATE TABLE AFW_25_ENGIN
(
  SEQNC              NUMBER(10),
  CODE               VARCHAR2(23 BYTE),
  REF_DV_FORMT_SORT  NUMBER(10),
  URL_SERVL          VARCHAR2(200 BYTE),
  DATE_CREAT         DATE,
  UTILS_CREAT        VARCHAR2(123 BYTE),
  DATE_MODFC         DATE,
  UTILS_MODFC        VARCHAR2(123 BYTE),
  URL_SERVL_EXTER    VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
