SET DEFINE OFF;
CREATE TABLE AFW_20_DOCMN
(
  SEQNC                  NUMBER(10),
  REF_PRODT_LANG         NUMBER(10),
  DATE_CREAT             DATE,
  UTILS_CREAT            VARCHAR2(123 BYTE),
  DATE_MODFC             DATE,
  UTILS_MODFC            VARCHAR2(123 BYTE),
  REF_STRUC_APLIC        NUMBER(10),
  REF_SEQNC_STRUC_APLIC  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
