SET DEFINE OFF;
CREATE TABLE AFW_25_PARMT_PUBLC_TRAVL_EXECT
(
  REF_TRAVL_PUBLC  NUMBER(10),
  VALR_NUMBR1      NUMBER,
  VALR_VARCH1      VARCHAR2(256 BYTE),
  VALR_DATE1       DATE,
  VALR_NUMBR2      NUMBER,
  VALR_VARCH2      VARCHAR2(256 BYTE),
  VALR_DATE2       DATE,
  VALR_NUMBR3      NUMBER,
  VALR_VARCH3      VARCHAR2(256 BYTE),
  VALR_DATE3       DATE,
  VALR_NUMBR4      NUMBER,
  VALR_VARCH4      VARCHAR2(256 BYTE),
  VALR_DATE4       DATE,
  VALR_NUMBR5      NUMBER,
  VALR_VARCH5      VARCHAR2(256 BYTE),
  VALR_DATE6       DATE,
  VALR_NUMBR7      NUMBER,
  VALR_VARCH7      VARCHAR2(256 BYTE),
  VALR_DATE7       DATE,
  VALR_NUMBR8      NUMBER,
  VALR_VARCH8      VARCHAR2(256 BYTE),
  VALR_DATE8       DATE,
  VALR_NUMBR9      NUMBER,
  VALR_VARCH9      VARCHAR2(256 BYTE),
  VALR_DATE9       DATE,
  VALR_NUMBR10     NUMBER,
  VALR_VARCH10     VARCHAR2(256 BYTE),
  VALR_DATE10      DATE,
  REF_TRAVL        NUMBER(10),
  SEQNC            NUMBER(10),
  VALR_DATE5       DATE,
  VALR_VARCH6      VARCHAR2(256 BYTE),
  VALR_NUMBR6      NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
