SET DEFINE OFF;
CREATE TABLE AFW_25_DOMN_TYPE_PUBLC
(
  SEQNC           NUMBER(10),
  REF_DOMN        NUMBER(10),
  REF_TYPE_PUBLC  NUMBER(10),
  REF_PUBLC       NUMBER(10),
  DATE_CREAT      DATE,
  UTILS_CREAT     VARCHAR2(123 BYTE),
  DATE_MODFC      DATE,
  UTILS_MODFC     VARCHAR2(123 BYTE),
  NOTE_BAS_PAGE   VARCHAR2(4000 BYTE),
  REF_THEME       NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
