SET DEFINE OFF;
CREATE TABLE AFW_17_COMPT_AXIAT
(
  SEQNC                 NUMBER(10),
  CODE                  VARCHAR2(23 BYTE),
  NOM                   VARCHAR2(60 BYTE),
  DESCR                 VARCHAR2(4000 BYTE),
  NUMR                  NUMBER(10),
  DATE_CREAT            DATE,
  UTILS_CREAT           VARCHAR2(123 BYTE),
  DATE_MODFC            DATE,
  UTILS_MODFC           VARCHAR2(123 BYTE),
  REF_DOMN              NUMBER(10),
  REF_PROFL_COURL       NUMBER(10),
  REF_PUBLC_PAGE_GARDE  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
