SET DEFINE OFF;
CREATE TABLE AFW_12_STRUC_APLIC
(
  SEQNC                    NUMBER(10),
  NOM                      VARCHAR2(100 BYTE),
  DESCR                    VARCHAR2(200 BYTE),
  REF_PRODT                NUMBER(10),
  DATE_CREAT               DATE,
  UTILS_CREAT              VARCHAR2(123 BYTE),
  DATE_MODFC               DATE,
  UTILS_MODFC              VARCHAR2(123 BYTE),
  CODE                     VARCHAR2(23 BYTE),
  REF_MESG_ERR_SUPRS       NUMBER(10),
  INDIC_EXTRA_TOUT         VARCHAR2(2 BYTE)     DEFAULT 'HE',
  TAIL_TABL_EXTRA          NUMBER(10),
  NOM_STRUC_ACCES_DON      VARCHAR2(30 BYTE),
  REF_PAGE_LISTE           NUMBER(10),
  REF_PAGE_FORML           NUMBER(10),
  NOM_PACKG                VARCHAR2(30 BYTE),
  DNR_REF_PRODT            NUMBER(10),
  INDIC_DISPN_DOCMN        VARCHAR2(1 BYTE)     DEFAULT 'N',
  NOM_SCHEM                VARCHAR2(30 BYTE),
  ICON_FONT_AWESM          VARCHAR2(200 BYTE),
  INDIC_DISPN_PROCS_APROB  VARCHAR2(1 BYTE)     DEFAULT 'N'
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
