SET DEFINE OFF;
CREATE TABLE AFW_11_PRODT_LANG
(
  SEQNC          NUMBER(10),
  REF_PRODT      NUMBER(10),
  REF_LANG       NUMBER(10),
  DATE_CREAT     DATE,
  UTILS_CREAT    VARCHAR2(123 BYTE),
  DATE_MODFC     DATE,
  UTILS_MODFC    VARCHAR2(123 BYTE),
  INDIC_DEFT     VARCHAR2(1 BYTE),
  DNR_REF_PRODT  NUMBER(10),
  ORDRE_PRESN    NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
