SET DEFINE OFF;
CREATE TABLE AFW_12_LIEN_GR_GADGT_GR_UTILS
(
  SEQNC                  NUMBER(10),
  REF_GROUP_GADGT_UTILS  NUMBER(10),
  REF_GROUP_UTILS        NUMBER(10),
  DATE_CREAT             DATE,
  UTILS_CREAT            VARCHAR2(123 BYTE),
  DATE_MODFC             DATE,
  UTILS_MODFC            VARCHAR2(123 BYTE),
  REF_UTILS              NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
