SET DEFINE OFF;
CREATE TABLE AFW_23_APLIC_MODL_RECHR
(
  SEQNC                        NUMBER(10),
  REF_MODL_RECHR               NUMBER(10),
  REF_STRUC_APLIC_RECHR        NUMBER(10),
  REF_STRUC_APLIC_LIEN         NUMBER(10),
  NOMBR_MAXIM_RESLT            NUMBER(4),
  UTILS_CREAT                  VARCHAR2(123 BYTE),
  DATE_CREAT                   DATE,
  UTILS_MODFC                  VARCHAR2(123 BYTE),
  DATE_MODFC                   DATE,
  REF_ATRIB_STRUC_APLIC_AFICH  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
