SET DEFINE OFF;
CREATE TABLE AFW_14_DOMN_VALR
(
  SEQNC               NUMBER(10),
  CODE                VARCHAR2(23 BYTE),
  NOM                 VARCHAR2(60 BYTE),
  DESCR               VARCHAR2(2000 BYTE),
  ENONC_SOURC         VARCHAR2(4000 BYTE),
  DATE_CREAT          DATE,
  UTILS_CREAT         VARCHAR2(123 BYTE),
  DATE_MODFC          DATE,
  UTILS_MODFC         VARCHAR2(123 BYTE),
  TYPE_DON            VARCHAR2(1 BYTE),
  REF_FORMT           NUMBER(10),
  REF_PRODT           NUMBER(10),
  REF_TYPE_DOMN_VALR  NUMBER(10),
  INDIC_SYSTM         VARCHAR2(1 BYTE)          DEFAULT 'N',
  DNR_REF_PRODT       NUMBER(10),
  REF_DOMN            NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
