SET DEFINE OFF;
CREATE TABLE AFW_25_CHAMP
(
  SEQNC              NUMBER(10),
  CODE               VARCHAR2(23 BYTE),
  POSTN_X            NUMBER(10),
  POSTN_Y            NUMBER(10),
  ANGLE_ORINT        NUMBER(10),
  REF_FORMT          NUMBER(10),
  REF_VERSN_PUBLC    NUMBER(10),
  REF_DV_TYPE_CHAMP  NUMBER(10),
  INDIC_MODIF        VARCHAR2(1 BYTE)           DEFAULT 'N',
  NOM                VARCHAR2(60 BYTE),
  DATE_CREAT         DATE,
  UTILS_CREAT        VARCHAR2(123 BYTE),
  DATE_MODFC         DATE,
  UTILS_MODFC        VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
