SET DEFINE OFF;
CREATE TABLE AFW_12_ARBRE
(
  SEQNC         NUMBER(10),
  NOEUD_ACTIF   VARCHAR2(60 BYTE),
  REF_SESN      NUMBER,
  DATE_CREAT    DATE,
  UTILS_CREAT   VARCHAR2(123 BYTE),
  DATE_MODFC    DATE,
  UTILS_MODFC   VARCHAR2(123 BYTE),
  INDIC_RAFRC   VARCHAR2(1 BYTE)                DEFAULT 'N',
  ID_APEX_REGN  NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
