SET DEFINE OFF;
CREATE TABLE AFW_25_PARMT_PUBLC_TRAVL
(
  SEQNC                 NUMBER(10),
  REF_PUBLC_TRAVL       NUMBER(10),
  REF_PARMT_TYPE_PUBLC  NUMBER(10),
  VALR_VARCH            VARCHAR2(4000 BYTE),
  VALR_DATE             DATE,
  VALR_NUMBR            NUMBER,
  DATE_CREAT            DATE,
  UTILS_CREAT           VARCHAR2(123 BYTE),
  DATE_MODFC            DATE,
  UTILS_MODFC           VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
