SET DEFINE OFF;
CREATE TABLE AFW_11_UTILS
(
  SEQNC        NUMBER(10),
  REF_PRODT    NUMBER(10),
  REF_UTILS    NUMBER(10),
  ROLE         VARCHAR2(5 BYTE),
  DATE_CREAT   DATE,
  UTILS_CREAT  VARCHAR2(123 BYTE),
  DATE_MODFC   DATE,
  UTILS_MODFC  VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
