SET DEFINE OFF;
CREATE TABLE AFW_17_COURL_ENTRA
(
  SEQNC            NUMBER(16),
  REF_PROFL_COURL  NUMBER(10),
  DATE_RECPT       DATE,
  DATE_COURL       DATE,
  OBJET            VARCHAR2(4000 BYTE),
  CONTN_TEXTE_PUR  CLOB,
  CONTN_HTML       CLOB,
  NOM_EXPED        VARCHAR2(500 BYTE),
  COURL_EXPED      VARCHAR2(2000 BYTE),
  INDIC_SUPRM      VARCHAR2(1 BYTE),
  INDIC_LU         VARCHAR2(1 BYTE),
  INDIC_RECNT      VARCHAR2(1 BYTE),
  INDIC_REPND      VARCHAR2(1 BYTE),
  TYPE_CONTN       VARCHAR2(100 BYTE),
  TAIL_MESG        NUMBER(10),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE)
)
LOB (CONTN_TEXTE_PUR) STORE AS BASICFILE (
  TABLESPACE  APEXFRAMEWORK
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOB (CONTN_HTML) STORE AS BASICFILE (
  TABLESPACE  APEXFRAMEWORK
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
