SET DEFINE OFF;
CREATE TABLE AFW_04_CONTX_ETEND
(
  SEQNC        NUMBER(10),
  REF_CONTX    NUMBER(10),
  NOM          VARCHAR2(30 BYTE),
  VALR_NUMBR   NUMBER(10),
  VALR_VARCH   VARCHAR2(4000 BYTE),
  DATE_CREAT   DATE,
  UTILS_CREAT  VARCHAR2(123 BYTE),
  DATE_MODFC   DATE,
  UTILS_MODFC  VARCHAR2(123 BYTE),
  PAGE_CIBLE   VARCHAR2(1 BYTE),
  TYPE_ALIMN   VARCHAR2(3 BYTE),
  TYPE_ELEMN   VARCHAR2(1 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
