SET DEFINE OFF;
CREATE TABLE AFW_12_TYPE_STRUC
(
  SEQNC        NUMBER(10),
  CODE         VARCHAR2(20 BYTE),
  NOM          VARCHAR2(100 BYTE),
  DESCR        VARCHAR2(2000 BYTE),
  DATE_CREAT   DATE,
  UTILS_CREAT  VARCHAR2(123 BYTE),
  DATE_MODFC   DATE,
  UTILS_MODFC  VARCHAR2(123 BYTE),
  REF_DOMN     NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
