SET DEFINE OFF;
CREATE TABLE AFW_13_RESRC
(
  SEQNC                   NUMBER(10),
  CODE                    VARCHAR2(60 BYTE),
  REF_PRODT               NUMBER(10),
  DESCR                   VARCHAR2(4000 BYTE),
  REF_TYPE_FICHR          NUMBER(10),
  REF_STRUC_APLIC         NUMBER(10),
  INDIC_STOCK_MEME_REPRT  VARCHAR2(1 BYTE)      DEFAULT 'O',
  DATE_CREAT              DATE,
  UTILS_CREAT             VARCHAR2(123 BYTE),
  DATE_MODFC              DATE,
  UTILS_MODFC             VARCHAR2(123 BYTE),
  TYPE_RESRC              VARCHAR2(5 BYTE)      DEFAULT 'SIMPL',
  NOM                     VARCHAR2(60 BYTE),
  NOM_PHYSQ_COMPS         VARCHAR2(100 BYTE),
  INDIC_PUBLC             VARCHAR2(1 BYTE)      DEFAULT 'N',
  EMPLA_HTML              VARCHAR2(11 BYTE)     DEFAULT 'HEADR',
  REF_PLUGN               NUMBER(10),
  REF_DOSR_VIRTL          NUMBER(10),
  DNR_REF_PRODT           NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
