SET DEFINE OFF;
CREATE TABLE AFW_21_PLUGN_CALND
(
  SEQNC                      NUMBER(10),
  ENONC_PRE_REQT             VARCHAR2(4000 BYTE),
  REF_DV_VUE_DEFT            NUMBER(10),
  CONCT_PROPR_ENTET_GAUCH    VARCHAR2(400 BYTE),
  CONCT_PROPR_ENTET_CENTR    VARCHAR2(400 BYTE),
  CONCT_PROPR_ENTET_DROIT    VARCHAR2(400 BYTE),
  INDIC_EVENM_MODFB          VARCHAR2(1 BYTE)   DEFAULT 'O',
  NOM_TABLE                  VARCHAR2(30 BYTE),
  COLN_TITRE                 VARCHAR2(30 BYTE),
  COLN_DESCR                 VARCHAR2(30 BYTE),
  COLN_TYPE                  VARCHAR2(30 BYTE),
  COLN_AIDE_INSTA            VARCHAR2(30 BYTE),
  COLN_LIEN                  VARCHAR2(30 BYTE),
  COLN_INDIC_JOURN_COMPL     VARCHAR2(30 BYTE),
  COLN_DATE_DEBUT            VARCHAR2(30 BYTE),
  COLN_DATE_FIN              VARCHAR2(30 BYTE),
  DATE_CREAT                 DATE,
  UTILS_CREAT                VARCHAR2(123 BYTE),
  DATE_MODFC                 DATE,
  UTILS_MODFC                VARCHAR2(123 BYTE),
  LARGR_REGN_CALND           NUMBER(4),
  COLN_TITRE_AIDE_INSTA      VARCHAR2(30 BYTE),
  INDIC_AGEND                VARCHAR2(1 BYTE)   DEFAULT 'N',
  AGEND_NOM_TABLE            VARCHAR2(30 BYTE),
  AGEND_COLN_TITRE           VARCHAR2(30 BYTE),
  COLN_VALR                  VARCHAR2(30 BYTE),
  AGEND_COLN_VALR            VARCHAR2(30 BYTE),
  AGEND_COLN_COULR           VARCHAR2(30 BYTE),
  CODE                       VARCHAR2(23 BYTE)  DEFAULT NULL,
  DNR_REF_PRODT              NUMBER(10),
  COLN_AGEND                 VARCHAR2(30 BYTE),
  COLN_IDENT                 VARCHAR2(30 BYTE),
  COLN_DATE_JOURN_COMPL      VARCHAR2(30 BYTE),
  COLN_DATE_FIN_JOURN_COMPL  VARCHAR2(30 BYTE),
  NOMBR_MINTS_INTER          NUMBER(4)          DEFAULT 30,
  HEURE_DEBUT_NORML          VARCHAR2(10 BYTE)  DEFAULT 8,
  HEURE_FIN_NORML            VARCHAR2(10 BYTE)  DEFAULT 17,
  HEURE_DEBUT_EXTEN          VARCHAR2(10 BYTE),
  HEURE_FIN_EXTEN            VARCHAR2(10 BYTE),
  COLN_INDIC_EVENM_MODFB     VARCHAR2(30 BYTE)  DEFAULT NULL,
  REF_PRODT                  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
