SET DEFINE OFF;
CREATE TABLE AFW_12_INSTA_PROCS_APROB
(
  SEQNC                        NUMBER(10),
  REF_GROUP_STAT               NUMBER(10),
  REF_STRUC_APLIC              NUMBER(10),
  REF_SEQNC_STRUC_APLIC        NUMBER(10),
  UTILS_CREAT                  VARCHAR2(123 BYTE),
  DATE_CREAT                   DATE,
  UTILS_MODFC                  VARCHAR2(123 BYTE),
  DATE_MODFC                   DATE,
  DNR_REF_DOMN                 NUMBER(10),
  REF_INSTA_PROCS_APROB_SUIVN  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
