SET DEFINE OFF;
CREATE TABLE AFW_36_VUE_ATRIB
(
  SEQNC             NUMBER(10),
  REF_VUE           NUMBER(10),
  REF_ATRIB_DISPN   NUMBER(10),
  DNR_REF_APLIC     NUMBER(10),
  UTILS_CREAT       VARCHAR2(123 BYTE),
  DATE_CREAT        DATE,
  UTILS_MODFC       VARCHAR2(123 BYTE),
  DATE_MODFC        DATE,
  POSTN_FILTR_BRIS  NUMBER(3),
  SENS_FILTR_BRIS   VARCHAR2(4 BYTE),
  POSTN_FILTR_DEFT  NUMBER(3),
  SENS_FILTR_DEFT   VARCHAR2(4 BYTE),
  ORDRE             NUMBER(3)                   DEFAULT 1
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
