SET DEFINE OFF;
CREATE TABLE AFW_12_LIEN_STRUC
(
  SEQNC             NUMBER(10),
  REF_STRUC_ADMIN   NUMBER(10),
  DATE_DEBUT_EFECT  DATE,
  DATE_FIN_EFECT    DATE,
  DATE_CREAT        DATE,
  UTILS_CREAT       VARCHAR2(123 BYTE),
  DATE_MODFC        DATE,
  UTILS_MODFC       VARCHAR2(123 BYTE),
  REF_STRUC_LIE     NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
