SET DEFINE OFF;
CREATE TABLE AFW_13_CONDT_EXECT
(
  SEQNC              NUMBER(10),
  CODE               VARCHAR2(23 BYTE),
  NOM                VARCHAR2(60 BYTE),
  DESCR              VARCHAR2(4000 BYTE),
  ENONC_CONDT_PLSQL  VARCHAR2(4000 BYTE),
  DATE_CREAT         DATE,
  UTILS_CREAT        VARCHAR2(123 BYTE),
  DATE_MODFC         DATE,
  UTILS_MODFC        VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
