SET DEFINE OFF;
CREATE TABLE AFW_13_EXPOR_APLIC
(
  SEQNC                   NUMBER(10),
  REF_SESN                NUMBER,
  REF_APLIC               NUMBER(10),
  INDIC_MAJ_REFRN         VARCHAR2(1 BYTE)      DEFAULT 'N',
  NUMR_APLIC_CIBLE        NUMBER,
  INDIC_AJOUT_APLIC_APEX  VARCHAR2(1 BYTE)      DEFAULT 'O'
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
