SET DEFINE OFF;
CREATE TABLE AFW_04_FIL_ARIAN
(
  SEQNC            NUMBER(10),
  PAGE             NUMBER(10),
  SESSION_ID       NUMBER,
  REF_ELEMN_SUP    NUMBER(10),
  LIBL             VARCHAR2(200 BYTE),
  TIMST            TIMESTAMP(6),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  APP_ID           NUMBER,
  HASH_DERNR_URL   RAW(16),
  INDIC_AFICH      VARCHAR2(1 BYTE),
  REF_NAVGT_HISTR  NUMBER(10),
  APLIC            NUMBER,
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE),
  INDIC_DUPLC      VARCHAR2(1 BYTE)             DEFAULT 'N',
  INDIC_VIRTL      VARCHAR2(1 BYTE)             DEFAULT 'N'
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
