SET DEFINE OFF;
CREATE TABLE AFW_01_HIERC_APLIC
(
  SEQNC                  NUMBER(10),
  REF_EVENM_NOTFB        NUMBER(10),
  APLIC_PRIOR            NUMBER(10),
  REF_ATRIB_STRUC_APLIC  NUMBER(10),
  DATE_CREAT             DATE,
  UTILS_CREAT            VARCHAR2(123 BYTE),
  DATE_MODFC             DATE,
  UTILS_MODFC            VARCHAR2(123 BYTE),
  DNR_REF_PRODT          NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
