SET DEFINE OFF;
CREATE TABLE AFW_30_ITEM_CARNT_PRODT
(
  SEQNC              NUMBER(10),
  NOM                VARCHAR2(200 BYTE),
  DESCR              VARCHAR2(4000 BYTE),
  REF_CARNT_PRODT    NUMBER(10),
  REF_DV_PRIOR       NUMBER(1),
  REF_STAT           NUMBER(10),
  REF_DV_TAIL_RELTV  NUMBER(10),
  REF_CAS_UTILS      NUMBER(10),
  DATE_CREAT         DATE,
  UTILS_CREAT        VARCHAR2(123 BYTE),
  DATE_MODFC         DATE,
  UTILS_MODFC        VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
