SET DEFINE OFF;
CREATE TABLE AFW_04_NAVGT_HISTR
(
  SEQNC        NUMBER(10),
  REF_UTILS    NUMBER(10),
  DNR_LIBL     VARCHAR2(60 BYTE),
  DNR_URL      VARCHAR2(200 BYTE),
  DNR_ICON     VARCHAR2(200 BYTE),
  DATE_CREAT   DATE,
  UTILS_CREAT  VARCHAR2(123 BYTE),
  DATE_MODFC   DATE,
  UTILS_MODFC  VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
