SET DEFINE OFF;
CREATE TABLE AFW_17_PROFL_COURL
(
  SEQNC                    NUMBER(10),
  DOMN                     VARCHAR2(100 BYTE),
  NOM_ENVOY                VARCHAR2(100 BYTE),
  ADRES_ENVOY              VARCHAR2(100 BYTE),
  DATE_CREAT               DATE,
  UTILS_CREAT              VARCHAR2(123 BYTE),
  DATE_MODFC               DATE,
  UTILS_MODFC              VARCHAR2(123 BYTE),
  CODE                     VARCHAR2(23 BYTE),
  SERVR_SORTN              VARCHAR2(100 BYTE),
  PORT_SORTN               NUMBER(5)            DEFAULT 25,
  AUTHE_METHD_SORTN        VARCHAR2(23 BYTE),
  AUTHE_USAGR_SORTN        VARCHAR2(100 BYTE),
  AUTHE_MDP_SORTN          VARCHAR2(100 BYTE),
  REF_DOMN                 NUMBER(10),
  NOM                      VARCHAR2(60 BYTE),
  DESCR                    VARCHAR2(4000 BYTE),
  INDIC_SSL_SORTN          VARCHAR2(1 BYTE)     DEFAULT 'N',
  SERVR_ENTRA              VARCHAR2(100 BYTE),
  PORT_ENTRA               NUMBER(5),
  INDIC_SSL_ENTRA          VARCHAR2(1 BYTE)     DEFAULT 'N',
  AUTHE_METHD_ENTRA        VARCHAR2(23 BYTE),
  AUTHE_USAGR_ENTRA        VARCHAR2(100 BYTE),
  AUTHE_MDP_ENTRA          VARCHAR2(100 BYTE),
  PROTC_ENTRA              VARCHAR2(5 BYTE)     DEFAULT 'IMAP',
  INDIC_LIRE_PROFL_ENTRA   VARCHAR2(1 BYTE)     DEFAULT 'N',
  INDIC_LECTR_ENTRA_ERR    VARCHAR2(1 BYTE)     DEFAULT 'N',
  INDIC_REPRS_LECTR_ENTRA  VARCHAR2(1 BYTE)     DEFAULT 'N',
  ADRES_SUPRT              VARCHAR2(100 BYTE),
  NOM_SUPRT                VARCHAR2(100 BYTE),
  INDIC_AJOUT_SUPRT_CCI    VARCHAR2(1 BYTE),
  DNR_REF_DOMN             NUMBER(10),
  INDIC_ENVIR_SUJET        VARCHAR2(1 BYTE)     DEFAULT 'N'
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
