SET DEFINE OFF;
CREATE TABLE AFW_20_DETL_DOCMN
(
  SEQNC            NUMBER(10),
  REF_DOCMN        NUMBER(10),
  REF_SECTN_DOCMN  NUMBER(10),
  REF_DETL_DOCMN   NUMBER(10),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE),
  VALR             VARCHAR2(4000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
