SET DEFINE OFF;
CREATE TABLE AFW_23_RECHR
(
  SEQNC           NUMBER(10),
  REF_UTILS       NUMBER(10),
  DATE_EXECT      DATE,
  UTILS_CREAT     VARCHAR2(123 BYTE),
  DATE_CREAT      DATE,
  UTILS_MODFC     VARCHAR2(123 BYTE),
  DATE_MODFC      DATE,
  REF_MODL_RECHR  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
