SET DEFINE OFF;
CREATE TABLE AFW_30_CAS_UTILS
(
  SEQNC            NUMBER(10),
  CODE             VARCHAR2(23 BYTE),
  NOM              VARCHAR2(200 BYTE),
  DESCR            VARCHAR2(4000 BYTE),
  DOCMN_REFRC      VARCHAR2(200 BYTE),
  REF_CARNT_PRODT  NUMBER(10),
  REF_STAT         NUMBER(10),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE),
  REF_UTILS_RESPN  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
