SET DEFINE OFF;
CREATE TABLE AFW_13_PAGE_ITEM_LANG
(
  SEQNC          NUMBER(10),
  REF_PAGE_ITEM  NUMBER(10),
  NOM            VARCHAR2(255 BYTE),
  REF_LANG       NUMBER(10),
  DATE_CREAT     DATE,
  UTILS_CREAT    VARCHAR2(123 BYTE),
  DATE_MODFC     DATE,
  UTILS_MODFC    VARCHAR2(123 BYTE),
  DNR_REF_APLIC  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
