SET DEFINE OFF;
CREATE TABLE AFW_12_LIEN_GROUP_UTILS
(
  SEQNC                NUMBER(10),
  REF_GROUP            NUMBER(10),
  REF_UTILS            NUMBER(10),
  DATE_DEBUT_EFECT     DATE                     DEFAULT NULL,
  DATE_FIN_EFECT       DATE,
  DATE_CREAT           DATE,
  UTILS_CREAT          VARCHAR2(123 BYTE),
  DATE_MODFC           DATE,
  UTILS_MODFC          VARCHAR2(123 BYTE),
  REF_GROUP_UTILS_LIE  NUMBER(10),
  DNR_REF_PRODT        NUMBER(10),
  REF_DOMN             NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
