SET DEFINE OFF;
CREATE TABLE AFW_20_SECTN_DOCMN
(
  SEQNC              NUMBER(10),
  REF_DV_TYPE_SECTN  NUMBER(10),
  REF_SECTN_DOCMN    NUMBER(10),
  REF_STRUC_APLIC    NUMBER(10),
  DATE_CREAT         DATE,
  UTILS_CREAT        VARCHAR2(123 BYTE),
  DATE_MODFC         DATE,
  UTILS_MODFC        VARCHAR2(123 BYTE),
  NOM                VARCHAR2(30 BYTE),
  TITRE              VARCHAR2(60 BYTE),
  DESCR              VARCHAR2(4000 BYTE),
  REF_FORMT          NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
