SET DEFINE OFF;
CREATE TABLE AFW_36_VUE_TRI_SECND
(
  SEQNC        NUMBER(10),
  REF_VUE      NUMBER(10),
  REF_SESN     NUMBER,
  REF_ATRIB    NUMBER(10),
  SENS_FILTR   VARCHAR2(4 BYTE),
  UTILS_CREAT  VARCHAR2(123 BYTE),
  DATE_CREAT   DATE,
  UTILS_MODFC  VARCHAR2(123 BYTE),
  DATE_MODFC   DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
