SET DEFINE OFF;
CREATE TABLE AFW_12_UTILS
(
  SEQNC                  NUMBER(10),
  NOM                    VARCHAR2(60 BYTE),
  PRENM                  VARCHAR2(60 BYTE),
  CODE_UTILS             VARCHAR2(30 BYTE),
  MOT_PASSE              RAW(2000),
  DATE_EXPIR             DATE,
  INDIC_VERL             VARCHAR2(1 BYTE),
  INDIC_CHANG_MOT_PASSE  VARCHAR2(1 BYTE),
  DATE_CREAT             DATE,
  UTILS_CREAT            VARCHAR2(123 BYTE),
  DATE_MODFC             DATE,
  UTILS_MODFC            VARCHAR2(123 BYTE),
  COURL                  VARCHAR2(200 BYTE),
  DERNR_PRODT_ACCES      VARCHAR2(23 BYTE),
  INDIC_ACTIF            VARCHAR2(1 BYTE)       DEFAULT 'N',
  DERNR_DOMN_ACCES       VARCHAR2(23 BYTE),
  REF_DV_COMPL_MAXM      NUMBER(10),
  CODE_UTILS_BASE_DON    VARCHAR2(30 BYTE),
  PARMT_AUTHE_EXTER_AFW  VARCHAR2(400 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
