SET DEFINE OFF;
CREATE TABLE AFW_12_LIEN_GADGT_UTILS_PARMT
(
  SEQNC                       NUMBER(10),
  REF_LIEN_GADGT_UTILS        NUMBER(10),
  REF_GADGT_PARMT             NUMBER(10),
  REF_DV_FORML_DON            NUMBER(10),
  REF_LIEN_GADGT_PARMT_RACRC  NUMBER(10),
  REF_GADGT_PARMT_RACRC       NUMBER(10),
  FORML_DON                   VARCHAR2(4000 BYTE),
  DATE_CREAT                  DATE,
  UTILS_CREAT                 VARCHAR2(123 BYTE),
  DATE_MODFC                  DATE,
  UTILS_MODFC                 VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
