SET DEFINE OFF;
CREATE TABLE AFW_12_SERVR_LDAP
(
  SEQNC        NUMBER(10),
  ADRES        VARCHAR2(200 BYTE),
  PORT         NUMBER(10),
  DATE_CREAT   DATE,
  UTILS_CREAT  VARCHAR2(123 BYTE),
  DATE_MODFC   DATE,
  UTILS_MODFC  VARCHAR2(123 BYTE),
  BASE_DN      VARCHAR2(400 BYTE),
  UTILS_CN     VARCHAR2(400 BYTE),
  MOT_PASSE    VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
