SET DEFINE OFF;
CREATE TABLE AFW_01_OCURN_SA_EVENM_NOTFB
(
  SEQNC                  NUMBER(16),
  REF_HIERC_APLIC        NUMBER(10),
  REF_CONFG_EVENM_NOTFB  NUMBER(10),
  DATE_CREAT             DATE,
  UTILS_CREAT            VARCHAR2(123 BYTE),
  DATE_MODFC             DATE,
  UTILS_MODFC            VARCHAR2(123 BYTE),
  REF_SEQNC_STRUC_APLIC  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
