SET DEFINE OFF;
CREATE TABLE AFW_36_ATRIB_DISPN
(
  SEQNC          NUMBER(10),
  REF_PAGE       NUMBER(10),
  REF_TYPE_DON   NUMBER(10),
  INDIC_DISPN    VARCHAR2(1 BYTE)               DEFAULT 'N',
  NOM_AFICH      VARCHAR2(200 BYTE),
  NOM_SQL        VARCHAR2(30 BYTE),
  DNR_REF_APLIC  NUMBER(10),
  UTILS_CREAT    VARCHAR2(123 BYTE),
  DATE_CREAT     DATE,
  UTILS_MODFC    VARCHAR2(123 BYTE),
  DATE_MODFC     DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
