SET DEFINE OFF;
CREATE TABLE AFW_12_GR_UT_OPERT_OPTIO_DOMN
(
  SEQNC            NUMBER(10),
  REF_GROUP_UTILS  NUMBER(10),
  REF_OPERT        NUMBER(10),
  REF_OPERT_OPTIO  NUMBER(10),
  REF_DOMN         NUMBER(10),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
