SET DEFINE OFF;
CREATE TABLE AFW_07_SEMPH
(
  SEQNC        NUMBER(10),
  CODE         VARCHAR2(23 BYTE),
  VARBL1       VARCHAR2(200 BYTE),
  VARBL2       VARCHAR2(200 BYTE),
  VARBL3       VARCHAR2(200 BYTE),
  DATE_CREAT   DATE,
  UTILS_CREAT  VARCHAR2(123 BYTE),
  INDIC_EXCLU  VARCHAR2(1 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
