SET DEFINE OFF;
CREATE TABLE AFW_13_INSTA_REGN_PILTB
(
  SEQNC             NUMBER(10),
  REF_UTILS         NUMBER(10),
  REF_REGN_PILTB    NUMBER(10),
  INDIC_REGN_ACTIV  VARCHAR2(1 BYTE)            DEFAULT 'O',
  DATE_CREAT        DATE,
  UTILS_CREAT       VARCHAR2(123 BYTE),
  DATE_MODFC        DATE,
  UTILS_MODFC       VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
