SET DEFINE OFF;
CREATE TABLE AFW_17_COURL_DESTN
(
  SEQNC          NUMBER(10),
  DATE_CREAT     DATE,
  UTILS_CREAT    VARCHAR2(123 BYTE),
  DATE_MODFC     DATE,
  UTILS_MODFC    VARCHAR2(123 BYTE),
  REF_FIL_ATENT  NUMBER(10),
  NOM            VARCHAR2(100 BYTE),
  ADRES          VARCHAR2(100 BYTE),
  TYPE           VARCHAR2(10 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
