SET DEFINE OFF;
CREATE TABLE AFW_37_GADGT_PARMT
(
  SEQNC            NUMBER(10),
  REF_GADGT        NUMBER(10),
  CODE             VARCHAR2(23 BYTE),
  NOM              VARCHAR2(250 BYTE),
  ORDRE_PRESN      NUMBER,
  INDIC_OBLIG      VARCHAR2(1 BYTE)             DEFAULT 'N',
  REF_DV_TYPE_DON  NUMBER(10),
  REF_DOMN_VALR    NUMBER(10),
  DESCR            VARCHAR2(4000 BYTE),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE),
  DNR_REF_PRODT    NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
