SET DEFINE OFF;
CREATE TABLE AFW_17_PROPR_COURL_ENTRA
(
  SEQNC            NUMBER(18),
  REF_COURL_ENTRA  NUMBER(16),
  NOM              VARCHAR2(100 BYTE),
  VALR             VARCHAR2(4000 BYTE),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
