SET DEFINE OFF;
CREATE TABLE AFW_12_INSTA_SCENR_NOTFC_LOG
(
  SEQNC                       NUMBER(10),
  REF_UTILS                   NUMBER(10),
  REF_STRUC_APLIC             NUMBER(10),
  REF_SEQNC_STRUC_APLIC       NUMBER(10),
  REF_INSTA_SCENR_NOTFC       NUMBER(10),
  REF_ATRIB_SCENR_NOTFC_ITEM  NUMBER(10),
  ID_ITEM_APEX                NUMBER,
  UTILS_CREAT                 VARCHAR2(123 BYTE),
  DATE_CREAT                  DATE,
  UTILS_MODFC                 VARCHAR2(123 BYTE),
  DATE_MODFC                  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
