SET DEFINE OFF;
CREATE TABLE AFW_21_PLUGN_CALND_COULR
(
  SEQNC        NUMBER(10),
  ORDRE_PRESN  NUMBER,
  COULR        VARCHAR2(7 BYTE),
  DATE_CREAT   DATE,
  UTILS_CREAT  VARCHAR2(123 BYTE),
  DATE_MODFC   DATE,
  UTILS_MODFC  VARCHAR2(123 BYTE),
  COULR_TEXT   VARCHAR2(7 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
