SET DEFINE OFF;
CREATE TABLE AFW_01_CODE_ERR_ORACL
(
  SEQNC        NUMBER(10),
  ERR_CODE     NUMBER(5),
  UTILS_CREAT  VARCHAR2(123 BYTE),
  DATE_CREAT   DATE,
  DATE_MODFC   DATE,
  UTILS_MODFC  VARCHAR2(123 BYTE),
  LIBL         VARCHAR2(255 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
