SET DEFINE OFF;
CREATE TABLE AFW_01_MESG
(
  SEQNC          NUMBER(10),
  NUMR_MESG      VARCHAR2(10 BYTE),
  REF_PRODT      NUMBER(10),
  DATE_CREAT     DATE,
  UTILS_CREAT    VARCHAR2(123 BYTE),
  DATE_MODFC     DATE,
  UTILS_MODFC    VARCHAR2(123 BYTE),
  DESCR          VARCHAR2(4000 BYTE),
  TYPE_MESG      VARCHAR2(1 BYTE),
  DNR_REF_PRODT  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
