SET DEFINE OFF;
CREATE TABLE AFW_12_LIEN_SA_SCENR_NOTFC
(
  SEQNC            NUMBER(10),
  REF_STRUC_APLIC  NUMBER(10),
  REF_SCENR_NOTFC  NUMBER(10),
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_CREAT       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  DNR_REF_PRODT    NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
