SET DEFINE OFF;
CREATE TABLE AFW_12_TUTRL
(
  SEQNC            NUMBER(10),
  REF_UTILS        NUMBER(10),
  REF_TUTRL        NUMBER(10),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  REF_ETAPE_TUTRL  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
