SET DEFINE OFF;
CREATE TABLE AFW_13_MIME_TYPE
(
  SEQNC           NUMBER(10),
  REF_TYPE_FICHR  NUMBER(10),
  EXT             VARCHAR2(10 BYTE),
  MIME_TYPE       VARCHAR2(200 BYTE),
  DATE_CREAT      DATE,
  UTILS_CREAT     VARCHAR2(123 BYTE),
  DATE_MODFC      DATE,
  UTILS_MODFC     VARCHAR2(123 BYTE),
  ORDRE_CHOIX     NUMBER(2)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
