SET DEFINE OFF;
CREATE TABLE AFW_12_ARBRE_NOEUD
(
  SEQNC        NUMBER(10),
  REF_ARBRE    NUMBER(10),
  NOEUD_OUVER  VARCHAR2(60 BYTE),
  DATE_CREAT   DATE,
  UTILS_CREAT  VARCHAR2(123 BYTE),
  DATE_MODFC   DATE,
  UTILS_MODFC  VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
