SET DEFINE OFF;
CREATE TABLE AFW_01_MODL_MESG_NOTFC
(
  SEQNC       NUMBER(10),
  CODE        VARCHAR2(23 BYTE),
  NOM         VARCHAR2(60 BYTE),
  DESCR       VARCHAR2(4000 BYTE),
  OBJET       VARCHAR2(200 BYTE),
  REF_DOMN    NUMBER(10),
  CORPS_MESG  CLOB
)
LOB (CORPS_MESG) STORE AS BASICFILE (
  TABLESPACE  APEXFRAMEWORK
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
