SET DEFINE OFF;
CREATE TABLE AFW_25_PARMT_TYPE_PUBLC
(
  SEQNC              NUMBER(10),
  REF_TYPE_PUBLC     NUMBER(10),
  REF_ENGIN          NUMBER(10),
  CODE               VARCHAR2(23 BYTE),
  NOM                VARCHAR2(60 BYTE),
  DESCR              VARCHAR2(4000 BYTE),
  INDIC_PRESN_APPEL  VARCHAR2(1 BYTE)           DEFAULT 'N',
  INDIC_FIXE         VARCHAR2(1 BYTE)           DEFAULT 'O',
  VALR_DEFT          VARCHAR2(200 BYTE),
  TYPE_VALR_DEFT     VARCHAR2(5 BYTE)           DEFAULT 'LITL',
  DATE_CREAT         DATE,
  UTILS_CREAT        VARCHAR2(123 BYTE),
  DATE_MODFC         DATE,
  UTILS_MODFC        VARCHAR2(123 BYTE),
  TYPE_DON           VARCHAR2(1 BYTE),
  ORDRE_PRESN        NUMBER(3),
  CARDN              VARCHAR2(1 BYTE),
  DNR_REF_PRODT      NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
