SET DEFINE OFF;
CREATE TABLE AFW_12_FONCT_STRUC_APLIC
(
  SEQNC            NUMBER(10),
  REF_FONCT        NUMBER(10),
  REF_STRUC_APLIC  NUMBER(10),
  DNR_REF_PRODT    NUMBER(10),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
