SET DEFINE OFF;
CREATE TABLE AFW_11_ATRIB_ENTIT
(
  SEQNC              NUMBER(10),
  NOM                VARCHAR2(60 BYTE),
  TYPE_DON           VARCHAR2(5 BYTE),
  COMPR_MIGRT        VARCHAR2(23 BYTE),
  REF_ENTIT          NUMBER(10),
  DATE_CREAT         DATE,
  UTILS_CREAT        VARCHAR2(123 BYTE),
  DATE_MODFC         DATE,
  UTILS_MODFC        VARCHAR2(123 BYTE),
  DNR_REF_PRODT      NUMBER(10),
  CODE               VARCHAR2(30 BYTE),
  REF_ENTIT_REFRN    NUMBER(10),
  INDIC_NOUVL_ATRIB  VARCHAR2(1 BYTE)           DEFAULT 'O'
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
