SET DEFINE OFF;
CREATE TABLE AFW_12_UTILS_AVATR
(
  SEQNC            NUMBER(10),
  REF_UTILS        NUMBER(10),
  REF_DOMN         NUMBER(10),
  LOGO_TAIL_LARGE  BLOB,
  LOGO_TAIL_MOYN   BLOB,
  LOGO_TAIL_PET    BLOB,
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE)
)
LOB (LOGO_TAIL_LARGE) STORE AS BASICFILE (
  TABLESPACE  APEXFRAMEWORK
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOB (LOGO_TAIL_MOYN) STORE AS BASICFILE (
  TABLESPACE  APEXFRAMEWORK
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOB (LOGO_TAIL_PET) STORE AS BASICFILE (
  TABLESPACE  APEXFRAMEWORK
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
