SET DEFINE OFF;
CREATE TABLE AFW_12_CACHE_DROIT_ACCES
(
  REF_SESN          NUMBER,
  CLE_ACCES         VARCHAR2(100 BYTE),
  INDIC_VERFC_REUS  VARCHAR2(1 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
