SET DEFINE OFF;
CREATE TABLE AFW_07_ETAT_SESN
(
  SEQNC        NUMBER(10),
  SESSION_ID   NUMBER,
  NOM          VARCHAR2(60 BYTE),
  VALR         VARCHAR2(4000 BYTE),
  DATE_CREAT   DATE,
  UTILS_CREAT  VARCHAR2(123 BYTE),
  DATE_MODFC   DATE,
  UTILS_MODFC  VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
