SET DEFINE OFF;
CREATE TABLE AFW_14_DETL_DOMN_VALR
(
  SEQNC             NUMBER(10),
  CODE_VALR         VARCHAR2(23 BYTE),
  VALR              VARCHAR2(2000 BYTE),
  REF_DOMN_VALR     NUMBER(10),
  SEQNC_PRESN       NUMBER(3),
  DATE_DEBUT_EFECT  DATE,
  DATE_FIN_EFECT    DATE,
  DATE_CREAT        DATE,
  UTILS_CREAT       VARCHAR2(123 BYTE),
  DATE_MODFC        DATE,
  UTILS_MODFC       VARCHAR2(123 BYTE),
  VALR_COURT        VARCHAR2(20 BYTE),
  VALR_ORGAN        VARCHAR2(4000 BYTE),
  DNR_REF_PRODT     NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
