SET DEFINE OFF;
CREATE TABLE AFW_29_CONTR
(
  SEQNC            NUMBER(10),
  CODE_CONTR       VARCHAR2(23 BYTE),
  NOM_STRUC_ACCES  VARCHAR2(61 BYTE),
  NOM              VARCHAR2(60 BYTE),
  DESCR            VARCHAR2(4000 BYTE),
  NIV_GRAVT        NUMBER(1),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE),
  REF_PRODT        NUMBER(10),
  DNR_REF_PRODT    NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
