SET DEFINE OFF;
CREATE TABLE AFW_12_DEFNT_ACCES
(
  SEQNC            NUMBER(10),
  REF_GROUP_UTILS  NUMBER(10),
  REF_UTILS        NUMBER(10),
  INDIC_ACCES      VARCHAR2(5 BYTE),
  INDIC_MODFC      VARCHAR2(5 BYTE),
  INDIC_SUPRS      VARCHAR2(5 BYTE),
  INDIC_CREAT      VARCHAR2(5 BYTE),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE),
  REF_OPERT        NUMBER(10),
  REF_STRUC_APLIC  NUMBER(10),
  DNR_REF_PRODT    NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
