SET DEFINE OFF;
CREATE TABLE AFW_12_DOMN_SERVR_LDAP
(
  SEQNC             NUMBER(10),
  REF_DOMN          NUMBER(10),
  REF_SERVR_LDAP    NUMBER(10),
  DATE_DEBUT_EFECT  DATE,
  DATE_FIN_EFECT    DATE,
  DATE_CREAT        DATE,
  UTILS_CREAT       VARCHAR2(123 BYTE),
  DATE_MODFC        DATE,
  UTILS_MODFC       VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
