SET DEFINE OFF;
CREATE TABLE AFW_19_FONCT
(
  SEQNC                   NUMBER(10),
  CODE                    VARCHAR2(23 BYTE),
  DATE_CREAT              DATE,
  UTILS_CREAT             VARCHAR2(123 BYTE),
  DATE_MODFC              DATE,
  UTILS_MODFC             VARCHAR2(123 BYTE),
  TITRE_ATRIB1            VARCHAR2(60 BYTE),
  REF_DV_TYPE_ATRIB1      NUMBER(10),
  VALR_DEFT_ATRIB1        VARCHAR2(200 BYTE),
  TITRE_ATRIB2            VARCHAR2(60 BYTE),
  TITRE_ATRIB3            VARCHAR2(60 BYTE),
  TITRE_ATRIB4            VARCHAR2(60 BYTE),
  TITRE_ATRIB5            VARCHAR2(60 BYTE),
  REF_DV_TYPE_ATRIB2      NUMBER(10),
  REF_DV_TYPE_ATRIB3      NUMBER(10),
  REF_DV_TYPE_ATRIB4      NUMBER(10),
  REF_DV_TYPE_ATRIB5      NUMBER(10),
  VALR_DEFT_ATRIB2        VARCHAR2(200 BYTE),
  VALR_DEFT_ATRIB3        VARCHAR2(200 BYTE),
  VALR_DEFT_ATRIB4        VARCHAR2(200 BYTE),
  VALR_DEFT_ATRIB5        VARCHAR2(200 BYTE),
  REF_DV_TYPE_ACTIO       NUMBER(10),
  EXPRE_ACTIO             VARCHAR2(4000 BYTE),
  REF_DV_TYPE_EXPRE       NUMBER(10),
  INDIC_AFECT_INPUT_HTML  VARCHAR2(1 BYTE)      DEFAULT 'O',
  INDIC_PREVN_ACTIO_DEFT  VARCHAR2(1 BYTE)      DEFAULT 'O',
  INDIC_CLE               VARCHAR2(1 BYTE)      DEFAULT 'O',
  INDIC_BOUTN             VARCHAR2(1 BYTE)      DEFAULT 'O',
  CONDT_PRISE_CHARG       VARCHAR2(200 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
