SET DEFINE OFF;
CREATE TABLE AFW_01_ELEMN_CONFG_EVENM_NOTFB
(
  SEQNC                  NUMBER(10),
  REF_CONFG_EVENM_NOTFB  NUMBER(10),
  CODE                   VARCHAR2(30 BYTE),
  IDENT_ACCES            VARCHAR2(4000 BYTE),
  IDENT_ACCES_FORMT      VARCHAR2(4000 BYTE),
  DATE_CREAT             DATE,
  UTILS_CREAT            VARCHAR2(123 BYTE),
  DATE_MODFC             DATE,
  UTILS_MODFC            VARCHAR2(123 BYTE),
  FORMT                  VARCHAR2(50 BYTE),
  DNR_REF_DOMN           NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
