SET DEFINE OFF;
CREATE TABLE AFW_25_THEME
(
  SEQNC            NUMBER(10),
  REF_GROUP_PUBLC  NUMBER(10),
  DNR_REF_PRODT    NUMBER(10),
  NOM              VARCHAR2(60 BYTE),
  DESCR            VARCHAR2(4000 BYTE),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
