SET DEFINE OFF;
CREATE TABLE AFW_23_DETL_APLIC_MODL_RECHR
(
  SEQNC                  NUMBER(10),
  REF_APLIC_MODL_RECHR   NUMBER(10),
  REF_ATRIB_STRUC_APLIC  NUMBER(10),
  REF_PATRN_RECHR        NUMBER(10),
  ORDRE_EXECT            NUMBER(3),
  PERTN                  NUMBER(3),
  UTILS_CREAT            VARCHAR2(123 BYTE),
  DATE_CREAT             DATE,
  UTILS_MODFC            VARCHAR2(123 BYTE),
  DATE_MODFC             DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
