SET DEFINE OFF;
CREATE TABLE AFW_25_JOURN_TRAVL_EXECT
(
  SEQNC              NUMBER(10),
  REF_DV_TYPE_ECRIT  NUMBER(10),
  REF_TRAVL          NUMBER(10),
  REF_PUBLC_TRAVL    NUMBER(10),
  DATE_JOURN         DATE,
  ENONC              VARCHAR2(4000 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
