SET DEFINE OFF;
CREATE TABLE AFW_12_GROUP_STAT
(
  SEQNC             NUMBER(10),
  REF_PRODT         NUMBER(10),
  CODE              VARCHAR2(23 BYTE),
  NOM               VARCHAR2(60 BYTE),
  DESCR             VARCHAR2(4000 BYTE),
  DATE_CREAT        DATE,
  UTILS_CREAT       VARCHAR2(123 BYTE),
  DATE_MODFC        DATE,
  UTILS_MODFC       VARCHAR2(123 BYTE),
  DNR_REF_PRODT     NUMBER(10),
  REF_DOMN          NUMBER(10),
  REF_STRUC_APLIC   NUMBER(10),
  INDIC_DISPN       VARCHAR2(1 BYTE)            DEFAULT 'N',
  DATE_DEBUT_EFECT  DATE,
  DATE_FIN_EFECT    DATE,
  REF_EVENM_NOTFB   NUMBER(10),
  DNR_REF_DOMN      NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
