SET DEFINE OFF;
CREATE TABLE AFW_11_SCHEM_PRODT
(
  SEQNC          NUMBER(10),
  CODE           VARCHAR2(30 BYTE),
  NOM            VARCHAR2(200 BYTE),
  DESCR          VARCHAR2(4000 BYTE),
  REF_VERSN      NUMBER(10),
  DNR_REF_PRODT  NUMBER(10),
  INDIC_DEPLM    VARCHAR2(1 BYTE)               DEFAULT 'N',
  UTILS_CREAT    VARCHAR2(123 BYTE),
  DATE_CREAT     DATE,
  UTILS_MODFC    VARCHAR2(123 BYTE),
  DATE_MODFC     DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
