SET DEFINE OFF;
CREATE TABLE AFW_03_CLAS_INTER
(
  SEQNC                  NUMBER(10),
  CODE                   VARCHAR2(23 BYTE),
  NOM                    VARCHAR2(100 BYTE),
  DESCR                  VARCHAR2(400 BYTE),
  DATE_CREAT             DATE,
  UTILS_CREAT            VARCHAR2(123 BYTE),
  DATE_MODFC             DATE,
  UTILS_MODFC            VARCHAR2(123 BYTE),
  REF_PRODT              NUMBER(10),
  REF_PROFL_COURL        NUMBER(10),
  INDIC_AVERT_AUTR_UNIQ  VARCHAR2(1 BYTE)       DEFAULT 'N'
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
