SET DEFINE OFF;
CREATE TABLE AFW_13_TUTRL
(
  SEQNC              NUMBER(10),
  CODE               VARCHAR2(23 BYTE),
  NOM                VARCHAR2(100 BYTE),
  DESCR              VARCHAR2(400 BYTE),
  DATE_CREAT         DATE,
  UTILS_CREAT        VARCHAR2(123 BYTE),
  DATE_MODFC         DATE,
  UTILS_MODFC        VARCHAR2(123 BYTE),
  INDIC_PREMR_CHARG  VARCHAR2(1 BYTE)           DEFAULT 'N',
  DNR_REF_PRODT      NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
