SET DEFINE OFF;
CREATE TABLE AFW_12_ACTIO_AUDIT
(
  SEQNC            NUMBER(10),
  REF_STRUC_APLIC  NUMBER(10),
  DNR_REF_PRODT    NUMBER(10),
  CODE             VARCHAR2(23 BYTE),
  NOM              VARCHAR2(60 BYTE),
  REF_MESG         NUMBER(10),
  DESCR            VARCHAR2(4000 BYTE),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
