SET DEFINE OFF;
CREATE TABLE AFW_25_VALR_CHAMP
(
  SEQNC            NUMBER(10),
  REF_CHAMP        NUMBER(10),
  REF_PUBLC_TRAVL  NUMBER(10),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE),
  VALR_NOMBR       NUMBER(10),
  VALR_DATE        DATE,
  VALR_VARCH       VARCHAR2(400 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
