SET DEFINE OFF;
CREATE TABLE AFW_36_VUE
(
  SEQNC          NUMBER(10),
  REF_PAGE       NUMBER(10),
  CODE           VARCHAR2(23 BYTE),
  NOM            VARCHAR2(60 BYTE),
  NOM_AFICH      VARCHAR2(30 BYTE),
  DESCR          VARCHAR2(4000 BYTE),
  DNR_REF_APLIC  NUMBER(10),
  UTILS_CREAT    VARCHAR2(123 BYTE),
  DATE_CREAT     DATE,
  UTILS_MODFC    VARCHAR2(123 BYTE),
  DATE_MODFC     DATE,
  REF_VUE        NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
