SET DEFINE OFF;
CREATE TABLE AFW_13_FORMT_RESRC
(
  SEQNC           NUMBER(10),
  CODE            VARCHAR2(23 BYTE),
  REF_PRODT       NUMBER(10),
  DESCR           VARCHAR2(4000 BYTE),
  REF_TYPE_FICHR  NUMBER(10),
  LARGR           NUMBER(4),
  HAUTR           NUMBER(4),
  DATE_CREAT      DATE,
  UTILS_CREAT     VARCHAR2(123 BYTE),
  DATE_MODFC      DATE,
  UTILS_MODFC     VARCHAR2(123 BYTE),
  NOM             VARCHAR2(60 BYTE),
  DNR_REF_PRODT   NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
