SET DEFINE OFF;
CREATE TABLE AFW_23_RESLT_RECHR
(
  SEQNC                      NUMBER(10),
  REF_RECHR                  NUMBER(10),
  UTILS_CREAT                VARCHAR2(123 BYTE),
  DATE_CREAT                 DATE,
  UTILS_MODFC                VARCHAR2(123 BYTE),
  DATE_MODFC                 DATE,
  DNR_LIBL_STRUC_APLIC_HTML  VARCHAR2(4000 BYTE),
  DNR_LIBL_STRUC_APLIC       VARCHAR2(1000 BYTE),
  DNR_PERTN                  NUMBER(5,2),
  DNR_LIEN                   VARCHAR2(4000 BYTE),
  DNR_DECMP_RESLT            NUMBER(4),
  REF_APLIC_MODL_RECHR       NUMBER(10),
  DNR_REF_STRUC_APLIC        NUMBER(10),
  REF_SEQNC_STRUC_APLIC      NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
