SET DEFINE OFF;
CREATE TABLE AFW_17_COURL_PIECE_JOINT
(
  SEQNC       NUMBER(10),
  REF_COURL   NUMBER(10),
  MIME_TYPE   VARCHAR2(100 BYTE),
  CONTN       BLOB,
  TAIL        NUMBER(12),
  NOM_FICHR   VARCHAR2(500 BYTE),
  MODE_ATACH  VARCHAR2(30 BYTE)
)
LOB (CONTN) STORE AS BASICFILE (
  TABLESPACE  APEXFRAMEWORK
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
