SET DEFINE OFF;
CREATE TABLE AFW_17_COMPT_TWILI
(
  SEQNC           NUMBER(10),
  CODE            VARCHAR2(23 BYTE),
  NOM             VARCHAR2(60 BYTE),
  DESCR           VARCHAR2(4000 BYTE),
  ACOUN_ID        VARCHAR2(100 BYTE),
  AUTHE_TOKEN     VARCHAR2(100 BYTE),
  REPRT_WALT      VARCHAR2(500 BYTE),
  MOT_PASSE_WALT  VARCHAR2(30 BYTE),
  DATE_CREAT      DATE,
  UTILS_CREAT     VARCHAR2(123 BYTE),
  DATE_MODFC      DATE,
  UTILS_MODFC     VARCHAR2(123 BYTE),
  NUMR            NUMBER(11),
  INDIC_PARTG     VARCHAR2(1 BYTE)              DEFAULT 'N',
  REF_DOMN        NUMBER(10),
  DNR_REF_DOMN    NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
