SET DEFINE OFF;
CREATE TABLE AFW_12_LIEN_GADGT_UTILS
(
  SEQNC                  NUMBER(10),
  REF_GADGT              NUMBER(10),
  REF_GROUP_GADGT_UTILS  NUMBER(10),
  NOM                    VARCHAR2(250 BYTE),
  DESCR                  VARCHAR2(4000 BYTE),
  DATE_CREAT             DATE,
  UTILS_CREAT            VARCHAR2(123 BYTE),
  DATE_MODFC             DATE,
  UTILS_MODFC            VARCHAR2(123 BYTE),
  REF_SESN               NUMBER
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
