SET DEFINE OFF;
CREATE TABLE AFW_30_PAGE
(
  SEQNC            NUMBER(10),
  REF_AFW_13_PAGE  NUMBER(10),
  NOM              VARCHAR2(200 BYTE),
  NUMR_APEX        NUMBER,
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
