SET DEFINE OFF;
CREATE TABLE AFW_01_MODL_AFICH_NOTFC
(
  SEQNC                 NUMBER(10),
  CODE                  VARCHAR2(23 BYTE),
  NOM                   VARCHAR2(60 BYTE),
  DESCR                 VARCHAR2(4000 BYTE),
  COULR_TEXTE           VARCHAR2(7 BYTE),
  TAIL_TEXTE            NUMBER(2)               DEFAULT 12,
  COULR_TITRE           VARCHAR2(7 BYTE),
  TAIL_TITRE            NUMBER(2)               DEFAULT 12,
  TEMPS_AFICH           NUMBER(2)               DEFAULT 0,
  REF_RESRC_ICON        NUMBER(10),
  REF_FORMT_RESRC_ICON  NUMBER(10),
  REF_OCURN_RESRC_ICON  NUMBER(10),
  REF_DOMN              NUMBER(10),
  DATE_CREAT            DATE,
  UTILS_CREAT           VARCHAR2(123 BYTE),
  DATE_MODFC            DATE,
  UTILS_MODFC           VARCHAR2(123 BYTE),
  REF_TYPE_COMNC        NUMBER(10),
  REF_MODL_COMNC        NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
