SET DEFINE OFF;
CREATE TABLE AFW_12_ATRIB_SCENR_NOTFC_ITEM
(
  SEQNC                  NUMBER(10),
  REF_PAGE               NUMBER(10),
  REF_PAGE_ITEM          NUMBER(10),
  REF_ATRIB_SCENR_NOTFC  NUMBER(10),
  UTILS_CREAT            VARCHAR2(123 BYTE),
  DATE_CREAT             DATE,
  UTILS_MODFC            VARCHAR2(123 BYTE),
  DATE_MODFC             DATE,
  DNR_REF_APLIC          NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
