SET DEFINE OFF;
CREATE TABLE AFW_14_DETL_DOMN_VALR_LANG
(
  SEQNC               NUMBER(10),
  REF_DETL_DOMN_VALR  NUMBER(10),
  REF_LANG            NUMBER(10),
  VALR                VARCHAR2(2000 BYTE),
  VALR_COURT          VARCHAR2(20 BYTE),
  VALR_ORGAN          VARCHAR2(4000 BYTE),
  DATE_CREAT          DATE,
  UTILS_CREAT         VARCHAR2(123 BYTE),
  DATE_MODFC          DATE,
  UTILS_MODFC         VARCHAR2(123 BYTE),
  DNR_REF_PRODT       NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
