SET DEFINE OFF;
CREATE TABLE AFW_13_INSTA_PREFR
(
  SEQNC            NUMBER(10),
  REF_PREFR        NUMBER(10),
  REF_UTILS        NUMBER(10),
  REF_SESN         NUMBER,
  VALR             VARCHAR2(200 BYTE),
  DATE_CREAT       DATE,
  UTILS_CREAT      VARCHAR2(123 BYTE),
  DATE_MODFC       DATE,
  UTILS_MODFC      VARCHAR2(123 BYTE),
  REF_STRUC_APLIC  NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
