SET DEFINE OFF;
CREATE TABLE AFW_36_TYPE_DON
(
  SEQNC             NUMBER(10),
  CODE              VARCHAR2(23 BYTE),
  NOM               VARCHAR2(60 BYTE),
  UTILS_CREAT       VARCHAR2(123 BYTE),
  DATE_CREAT        DATE,
  UTILS_MODFC       VARCHAR2(123 BYTE),
  DATE_MODFC        DATE,
  MESG_PLACE_HOLDR  VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
