SET DEFINE OFF;
CREATE TABLE AFW_30_CARNT_SPRIN
(
  SEQNC             NUMBER(10),
  DESCR             VARCHAR2(4000 BYTE),
  REF_UTILS_RESPN   NUMBER(10),
  REF_CARNT_PRODT   NUMBER(10),
  DATE_DEBUT_PREVU  DATE,
  DATE_FIN_PREVU    DATE,
  REF_VERSN         NUMBER(10),
  DATE_CREAT        DATE,
  UTILS_CREAT       VARCHAR2(123 BYTE),
  DATE_MODFC        DATE,
  UTILS_MODFC       VARCHAR2(123 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING
/
