SET DEFINE OFF;
ALTER TABLE AFW_12_STRUC_APLIC ADD (
  CONSTRAINT AFW_12_STRUC_APLIC_CK1
  CHECK ((INDIC_EXTRA_TOUT = 'N' AND TAIL_TABL_EXTRA is not null) OR
INDIC_EXTRA_TOUT in ('O', 'HE'))
  ENABLE VALIDATE)
/
