SET DEFINE OFF;
ALTER TABLE AFW_21_PLUGN_ARBRE_NOEUD ADD (
  CONSTRAINT AFW_21_PLUGN_ARBRE_NOEUD_FK2 
  FOREIGN KEY (REF_RESRC) 
  REFERENCES AFW_13_RESRC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
