SET DEFINE OFF;
ALTER TABLE AFW_01_OCURN_SA_EVENM_NOTFB ADD (
  CONSTRAINT AFW_01_OCURN_SA_EVENM_NOTF_FK1 
  FOREIGN KEY (REF_HIERC_APLIC) 
  REFERENCES AFW_01_HIERC_APLIC (SEQNC)
  ENABLE VALIDATE)
/
