SET DEFINE OFF;
ALTER TABLE AFW_25_PARMT_PUBLC_TRAVL ADD (
  CONSTRAINT AFW_25_PARMT_PUBLC_TRAVL_FK1 
  FOREIGN KEY (REF_PUBLC_TRAVL) 
  REFERENCES AFW_25_PUBLC_TRAVL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
