SET DEFINE OFF;
ALTER TABLE AFW_25_PUBLC_TRAVL ADD (
  CONSTRAINT AFW_25_PUBLC_TRAVL_FK1 
  FOREIGN KEY (REF_VERSN_PUBLC) 
  REFERENCES AFW_25_VERSN_PUBLC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
