SET DEFINE OFF;
ALTER TABLE AFW_13_EMPLA_DOSR_VIRTL ADD (
  CONSTRAINT AFW_13_EMPLA_DOSR_VIRTL_FK1 
  FOREIGN KEY (REF_DOSR_VIRTL) 
  REFERENCES AFW_13_DOSR_VIRTL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
