SET DEFINE OFF;
ALTER TABLE AFW_13_ETAPE_TUTRL ADD (
  CONSTRAINT AFW_13_ETAPE_TUTRL_FK2 
  FOREIGN KEY (REF_PAGE_ITEM) 
  REFERENCES AFW_13_PAGE_ITEM (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
