SET DEFINE OFF;
ALTER TABLE AFW_12_SCENR_NOTFC_ACTIO ADD (
  CONSTRAINT AFW_12_SCENR_NOTFC_ACTIO_FK1 
  FOREIGN KEY (REF_SCENR_NOTFC) 
  REFERENCES AFW_12_SCENR_NOTFC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
