SET DEFINE OFF;
ALTER TABLE AFW_12_SCENR_NOTFC_ACTIO ADD (
  CONSTRAINT AFW_12_SCENR_NOTFC_ACTIO_FK3 
  FOREIGN KEY (REF_STAT) 
  REFERENCES AFW_12_STAT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
