SET DEFINE OFF;
ALTER TABLE AFW_36_VUE_ATRIB ADD (
  CONSTRAINT AFW_36_VUE_ATRIB_FK2 
  FOREIGN KEY (REF_ATRIB_DISPN) 
  REFERENCES AFW_36_ATRIB_DISPN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
