SET DEFINE OFF;
ALTER TABLE AFW_25_PARMT_PUBLC_TRAVL_EXECT ADD (
  CONSTRAINT AFW_25_PARMT_PUBLC_TRAVL_E_FK2 
  FOREIGN KEY (REF_TRAVL) 
  REFERENCES AFW_25_TRAVL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
