SET DEFINE OFF;
ALTER TABLE AFW_14_DETL_DOMN_VALR_LANG ADD (
  CONSTRAINT AFW_14_DETL_DOMN_VALR_LANG_FK1 
  FOREIGN KEY (REF_DETL_DOMN_VALR) 
  REFERENCES AFW_14_DETL_DOMN_VALR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
