SET DEFINE OFF;
ALTER TABLE AFW_01_DESTN_CONFG_EVENM_NOTFB ADD (
  CONSTRAINT AFW_01_DESTN_CONFG_EVENM_FK6 
  FOREIGN KEY (REF_ATRIB_SA_ADRES_DESTN) 
  REFERENCES AFW_12_ATRIB_STRUC_APLIC (SEQNC)
  ENABLE VALIDATE)
/
