SET DEFINE OFF;
ALTER TABLE AFW_25_PARMT_TYPE_PUBLC ADD (
  CONSTRAINT AFW_25_PARMT_TYPE_PUBLC_CK3
  CHECK ((INDIC_PRESN_APPEL = 'N' AND ORDRE_PRESN IS NOT NULL) OR (INDIC_PRESN_APPEL != 'N'))
  ENABLE VALIDATE)
/
