SET DEFINE OFF;
ALTER TABLE AFW_12_ATRIB_STRUC_APLIC ADD (
  CONSTRAINT AFW_12_ATRIB_STRUC_APLIC_FK3 
  FOREIGN KEY (REF_ATRIB_STRUC_APLIC) 
  REFERENCES AFW_12_ATRIB_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
