SET DEFINE OFF;
ALTER TABLE AFW_13_INSTA_REGN_PILTB ADD (
  CONSTRAINT AFW_13_INSTA_REGN_PILTB_FK1 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES AFW_12_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
