SET DEFINE OFF;
ALTER TABLE AFW_11_ENTIT ADD (
  CONSTRAINT AFW_11_ENTIT_FK2 
  FOREIGN KEY (REF_ATRIB_ENTIT_SUPR) 
  REFERENCES AFW_11_ATRIB_ENTIT (SEQNC)
  ON DELETE SET NULL
  DISABLE NOVALIDATE)
/
