SET DEFINE OFF;
ALTER TABLE AFW_21_PLUGN_ARBRE ADD (
  CONSTRAINT AFW_21_PLUGN_ARBRE_FK2 
  FOREIGN KEY (REF_PLUGN_ARBRE_NOEUD) 
  REFERENCES AFW_21_PLUGN_ARBRE_NOEUD (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE)
/
