SET DEFINE OFF;
ALTER TABLE AFW_12_INSTA_SCENR_NOTFC_LOG ADD (
  CONSTRAINT AFW_12_INSTA_SN_LOG_FK1 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES AFW_12_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
