SET DEFINE OFF;
ALTER TABLE AFW_25_JOURN_TRAVL_EXECT ADD (
  CONSTRAINT AFW_25_JOURN_TRAVL_EXECT_FK3 
  FOREIGN KEY (REF_DV_TYPE_ECRIT) 
  REFERENCES AFW_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE)
/
