SET DEFINE OFF;
ALTER TABLE AFW_13_LIEN_CONDT_PILTB ADD (
  CONSTRAINT AFW_13_LIEN_CONDT_PILTB_FK2 
  FOREIGN KEY (REF_CONDT_PILTB) 
  REFERENCES AFW_13_CONDT_PILTB (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
