SET DEFINE OFF;
ALTER TABLE AFW_01_MESG_INFOR ADD (
  CONSTRAINT AFW_01_MESG_INFOR_CK1
  CHECK ((SESS_ID is not null and REF_UTILS is null) or (SESS_ID is null and
REF_UTILS is not null))
  ENABLE VALIDATE)
/
