SET DEFINE OFF;
ALTER TABLE AFW_13_ETAPE_TUTRL ADD (
  CONSTRAINT AFW_13_ETAPE_TUTRL_FK8 
  FOREIGN KEY (REF_ETAPE_TUTRL_SUIVN) 
  REFERENCES AFW_13_ETAPE_TUTRL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
