SET DEFINE OFF;
ALTER TABLE AFW_12_INSTA_REGLE_APROB ADD (
  CONSTRAINT AFW_12_INSTA_REGLE_APROB_FK4 
  FOREIGN KEY (REF_INSTA_PROCS_APROB_STAT) 
  REFERENCES AFW_12_INSTA_PROCS_APROB_STAT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
