SET DEFINE OFF;
ALTER TABLE AFW_13_LIEN_CONDT_PILTB ADD (
  CONSTRAINT AFW_13_LIEN_CONDT_PILTB_FK1 
  FOREIGN KEY (REF_PAGE_ITEM) 
  REFERENCES AFW_13_PAGE_ITEM (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
