SET DEFINE OFF;
ALTER TABLE AFW_01_PROPG_EVENM_NOTFB ADD (
  CONSTRAINT AFW_01_PROPG_EVENM_NOTFB_FK2 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES AFW_12_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
