SET DEFINE OFF;
ALTER TABLE AFW_30_ITEM_CARNT_SPRIN ADD (
  CONSTRAINT AFW_30_ITEM_CARNT_SPRIN_FK2 
  FOREIGN KEY (REF_ITEM_CARNT_PRODT) 
  REFERENCES AFW_30_ITEM_CARNT_PRODT (SEQNC)
  ENABLE VALIDATE)
/
