SET DEFINE OFF;
ALTER TABLE AFW_36_FILTR_SESN ADD (
  CONSTRAINT AFW_36_FILTR_SESN_FK2 
  FOREIGN KEY (REF_OPERT_FILTR) 
  REFERENCES AFW_36_OPERT_FILTR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
