SET DEFINE OFF;
ALTER TABLE AFW_01_ELEMN_CONFG_EVENM_NOTFB ADD (
  CONSTRAINT AFW_01_ELEMN_CONFG_EN_FK1 
  FOREIGN KEY (REF_CONFG_EVENM_NOTFB) 
  REFERENCES AFW_01_CONFG_EVENM_NOTFB (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
