SET DEFINE OFF;
ALTER TABLE AFW_12_CACHE_DROIT_ACCES ADD (
  CONSTRAINT AFW_12_CACHE_DROIT_ACCES_FK1 
  FOREIGN KEY (REF_SESN) 
  REFERENCES APEX_050000.WWV_FLOW_SESSIONS$ (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
