SET DEFINE OFF;
ALTER TABLE AFW_01_DESTN_CONFG_EVENM_NOTFB ADD (
  CONSTRAINT AFW_01_DESTN_CONFG_EVENM_FK5 
  FOREIGN KEY (REF_ATRIB_SA_NOM_FORMT) 
  REFERENCES AFW_12_ATRIB_STRUC_APLIC (SEQNC)
  ENABLE VALIDATE)
/
