SET DEFINE OFF;
ALTER TABLE AFW_12_FONCT_STRUC_APLIC ADD (
  CONSTRAINT AFW_12_FONCT_STRUC_APLIC_FK1 
  FOREIGN KEY (REF_FONCT) 
  REFERENCES AFW_12_FONCT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
