SET DEFINE OFF;
ALTER TABLE AFW_17_COURL_DESTN ADD (
  CONSTRAINT AFW_17_FIL_ATENT_DESTN_FK1 
  FOREIGN KEY (REF_FIL_ATENT) 
  REFERENCES AFW_17_COURL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
