SET DEFINE OFF;
ALTER TABLE AFW_12_REGLE_APROB ADD (
  CONSTRAINT AFW_12_REGLE_APROB_FK1 
  FOREIGN KEY (REF_GROUP_APROB) 
  REFERENCES AFW_12_GROUP_APROB (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
