SET DEFINE OFF;
ALTER TABLE AFW_12_INSTA_SCENR_NOTFC ADD (
  CONSTRAINT AFW_12_INSTA_SCENR_NOTFC_FK1 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES AFW_12_DOMN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
