SET DEFINE OFF;
ALTER TABLE AFW_12_ATRIB_SCENR_NOTFC ADD (
  CONSTRAINT AFW_12_ATRIB_SCENR_NOTFC_FK1 
  FOREIGN KEY (REF_ATRIB_STRUC_APLIC) 
  REFERENCES AFW_12_ATRIB_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
