SET DEFINE OFF;
ALTER TABLE AFW_12_REGLE_APROB ADD (
  CONSTRAINT AFW_12_REGLE_APROB_FK3 
  FOREIGN KEY (REF_EVOLT_STAT) 
  REFERENCES AFW_12_EVOLT_STAT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
