SET DEFINE OFF;
ALTER TABLE AFW_01_OCURN_SA_EVENM_NOTFB ADD (
  CONSTRAINT AFW_01_OCURN_SA_EVENM_NOTF_FK2 
  FOREIGN KEY (REF_CONFG_EVENM_NOTFB) 
  REFERENCES AFW_01_CONFG_EVENM_NOTFB (SEQNC)
  ENABLE VALIDATE)
/
