SET DEFINE OFF;
ALTER TABLE AFW_25_PARMT_PUBLC_TRAVL_EXECT ADD (
  CONSTRAINT AFW_25_PARMT_PUBLC_TRAVL_E_FK1 
  FOREIGN KEY (REF_TRAVL_PUBLC) 
  REFERENCES AFW_25_PUBLC_TRAVL (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
