SET DEFINE OFF;
ALTER TABLE AFW_12_GROUP_STAT ADD (
  CONSTRAINT AFW_12_GROUP_STAT_FK4 
  FOREIGN KEY (REF_EVENM_NOTFB) 
  REFERENCES AFW_01_EVENM_NOTFB (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE)
/
