SET DEFINE OFF;
ALTER TABLE AFW_07_AUDIT_STRUC_APLIC ADD (
  CONSTRAINT AFW_07_AUDIT_STRUC_APLIC_FK3 
  FOREIGN KEY (REF_ACTIO_AUDIT) 
  REFERENCES AFW_12_ACTIO_AUDIT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
