SET DEFINE OFF;
ALTER TABLE AFW_25_VERSN_PUBLC_SUBST ADD (
  CONSTRAINT AFW_25_VERSN_PUBLC_SUBST_FK2 
  FOREIGN KEY (REF_VERSN_PUBLC_SUBST) 
  REFERENCES AFW_25_VERSN_PUBLC_SUBST (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
