SET DEFINE OFF;
ALTER TABLE AFW_30_ITEM_CARNT_PRODT ADD (
  CONSTRAINT AFW_30_ITEM_CARNT_PRODT_FK2 
  FOREIGN KEY (REF_CAS_UTILS) 
  REFERENCES AFW_30_CAS_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
