SET DEFINE OFF;
ALTER TABLE AFW_01_DESTN_CONFG_EVENM_NOTFB ADD (
  CONSTRAINT AFW_01_DESTN_CONFG_EVENM_FK4 
  FOREIGN KEY (REF_RESLT_DESTN) 
  REFERENCES AFW_01_RESLT_DESTN (SEQNC)
  ENABLE VALIDATE)
/
