SET DEFINE OFF;
ALTER TABLE AFW_07_VALR_AUDIT_STRUC_APLIC ADD (
  CONSTRAINT AFW_07_VALR_AUDIT_SA_FK1 
  FOREIGN KEY (REF_AUDIT_STRUC_APLIC) 
  REFERENCES AFW_07_AUDIT_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
