SET DEFINE OFF;
ALTER TABLE AFW_03_LIEN_CLAS_INTER_UTILS ADD (
  CONSTRAINT AFW_03_LIEN_CLAS_INTER_UTI_FK1 
  FOREIGN KEY (REF_CLAS_INTER) 
  REFERENCES AFW_03_CLAS_INTER (SEQNC)
  ENABLE VALIDATE)
/
