SET DEFINE OFF;
ALTER TABLE AFW_12_LIEN_ROLE_APROB ADD (
  CONSTRAINT AFW_12_LIEN_ROLE_APROB_FK1 
  FOREIGN KEY (REF_ROLE_APROB) 
  REFERENCES AFW_12_ROLE_APROB (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
