SET DEFINE OFF;
ALTER TABLE AFW_25_VALR_ELEMN_CONFG ADD (
  CONSTRAINT AFW_25_VALR_ELEMN_CONFG_FK2 
  FOREIGN KEY (REF_ELEMN_CONFG_PUBLC) 
  REFERENCES AFW_25_ELEMN_CONFG_PUBLC (SEQNC)
  ENABLE VALIDATE)
/
