SET DEFINE OFF;
ALTER TABLE AFW_12_STRUC_APLIC_LANG ADD (
  CONSTRAINT AFW_12_STRUC_APLIC_LANG_FK1 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES AFW_12_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
