SET DEFINE OFF;
ALTER TABLE AFW_12_INSTA_PROCS_APROB ADD (
  CONSTRAINT AFW_12_INSTA_PROCS_APROB_FK2 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES AFW_12_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
