SET DEFINE OFF;
ALTER TABLE AFW_13_ITEM_MENU ADD (
  CONSTRAINT AFW_13_ITEM_MENU_FK16 
  FOREIGN KEY (REF_DV_VALR_SSPI) 
  REFERENCES AFW_14_DETL_DOMN_VALR (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE)
/
