SET DEFINE OFF;
ALTER TABLE AFW_12_LIEN_SA_SCENR_NOTFC ADD (
  CONSTRAINT AFW_12_LIEN_SA_SCENR_NOTFC_FK2 
  FOREIGN KEY (REF_SCENR_NOTFC) 
  REFERENCES AFW_12_SCENR_NOTFC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
