SET DEFINE OFF;
ALTER TABLE AFW_12_LIEN_GADGT_UTILS ADD (
  CONSTRAINT AFW_12_LIEN_GADGT_UTILS_FK1 
  FOREIGN KEY (REF_GADGT) 
  REFERENCES AFW_37_GADGT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
