SET DEFINE OFF;
ALTER TABLE AFW_01_MESG_ERR_LIE ADD (
  CONSTRAINT AFW_01_MESG_ERR_LIE_UK1
  UNIQUE (REF_CODE_ERR_ORACL, NOM_TABLE, NOM_COLN, NOM_CONTR, PAGE, REF_PRODT, TYPE_LIAIS, REF_MESG)
  ENABLE VALIDATE)
/
