SET DEFINE OFF;
ALTER TABLE AFW_12_INSTA_SCENR_NOTFC ADD (
  CONSTRAINT AFW_12_INSTA_SCENR_NOTFC_FK3 
  FOREIGN KEY (REF_SCENR_NOTFC_ACTIO) 
  REFERENCES AFW_12_SCENR_NOTFC_ACTIO (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
