SET DEFINE OFF;
ALTER TABLE AFW_12_SCENR_NOTFC_ACTIO ADD (
  CONSTRAINT AFW_12_SCENR_NOTFC_ACTIO_FK4 
  FOREIGN KEY (REF_EVENM_NOTFB) 
  REFERENCES AFW_01_EVENM_NOTFB (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
