SET DEFINE OFF;
ALTER TABLE AFW_12_INSTA_SCENR_NOTFC_LOG ADD (
  CONSTRAINT AFW_12_INSTA_SN_LOG_FK4 
  FOREIGN KEY (REF_ATRIB_SCENR_NOTFC_ITEM) 
  REFERENCES AFW_12_ATRIB_SCENR_NOTFC_ITEM (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
