SET DEFINE OFF;
ALTER TABLE AFW_30_AFECT_ITEM ADD (
  CONSTRAINT AFW_30_AFECT_ITEM_FK1 
  FOREIGN KEY (REF_ITEM_CARNT_PRODT) 
  REFERENCES AFW_30_ITEM_CARNT_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
