SET DEFINE OFF;
ALTER TABLE AFW_12_LIEN_GADGT_UTILS_PARMT ADD (
  CONSTRAINT AFW_12_LIEN_GADGT_UTILS_P_FK1 
  FOREIGN KEY (REF_LIEN_GADGT_UTILS) 
  REFERENCES AFW_12_LIEN_GADGT_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
