SET DEFINE OFF;
ALTER TABLE AFW_30_ITEM_CARNT_SPRIN ADD (
  CONSTRAINT AFW_30_ITEM_CARNT_SPRIN_FK1 
  FOREIGN KEY (REF_CARNT_SPRIN) 
  REFERENCES AFW_30_CARNT_SPRIN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
