SET DEFINE OFF;
ALTER TABLE AFW_12_INSTA_PROCS_APROB_STAT ADD (
  CONSTRAINT AFW_12_IP_APROB_FK1 
  FOREIGN KEY (REF_INSTA_PROCS_APROB) 
  REFERENCES AFW_12_INSTA_PROCS_APROB (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
