SET DEFINE OFF;
ALTER TABLE AFW_12_LIEN_GADGT_UTILS_PARMT ADD (
  CONSTRAINT AFW_12_LIEN_GADGT_UTILS_P_FK2 
  FOREIGN KEY (REF_GADGT_PARMT) 
  REFERENCES AFW_37_GADGT_PARMT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
