SET DEFINE OFF;
ALTER TABLE AFW_12_SCENR_NOTFC_ACTIO ADD (
  CONSTRAINT AFW_12_SCENR_NOTFC_ACTIO_FK2 
  FOREIGN KEY (REF_STRUC_APLIC_STAT) 
  REFERENCES AFW_12_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
