SET DEFINE OFF;
ALTER TABLE AFW_03_LIEN_CLAS_INTER_UTILS ADD (
  CONSTRAINT AFW_03_LIEN_CLAS_INTER_UTI_FK3 
  FOREIGN KEY (REF_GROUP_UTILS) 
  REFERENCES AFW_12_GROUP_UTILS (SEQNC)
  ENABLE VALIDATE)
/
