SET DEFINE OFF;
ALTER TABLE AFW_12_GROUP_GADGT_UTILS ADD (
  CONSTRAINT AFW_12_GROUP_GADGT_UTILS_FK2 
  FOREIGN KEY (REF_TABL_BORD) 
  REFERENCES AFW_37_TABL_BORD (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
