SET DEFINE OFF;
ALTER TABLE AFW_30_HISTR_EFORT_RESTN ADD (
  CONSTRAINT AFW_30_HISTR_EFORT_RESTN_FK1 
  FOREIGN KEY (REF_ITEM_CARNT_SPRIN) 
  REFERENCES AFW_30_ITEM_CARNT_SPRIN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
