SET DEFINE OFF;
ALTER TABLE AFW_21_PLUGN_CALND_TYPE ADD (
  CONSTRAINT AFW_21_PLUGN_CALND_TYPE_FK1 
  FOREIGN KEY (REF_DOMN) 
  REFERENCES AFW_12_DOMN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
