SET DEFINE OFF;
ALTER TABLE AFW_12_LIEN_STRUC ADD (
  CONSTRAINT AFW_12_LIEN_STRUC_FK3 
  FOREIGN KEY (REF_STRUC_LIE) 
  REFERENCES AFW_12_STRUC_ADMIN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
