SET DEFINE OFF;
ALTER TABLE AFW_21_PLUGN_ITEM_MENU ADD (
  CONSTRAINT AFW_21_PLUGN_ITEM_MENU_FK2 
  FOREIGN KEY (REF_PLUGN_MENU) 
  REFERENCES AFW_21_PLUGN_MENU (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
