SET DEFINE OFF;
ALTER TABLE AFW_23_DETL_APLIC_MODL_RECHR ADD (
  CONSTRAINT AFW_23_DETL_APLIC_MODL_REC_FK1 
  FOREIGN KEY (REF_APLIC_MODL_RECHR) 
  REFERENCES AFW_23_APLIC_MODL_RECHR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
