SET DEFINE OFF;
ALTER TABLE AFW_12_ATRIB_SCENR_NOTFC_ITEM ADD (
  CONSTRAINT AFW_12_ASN_ITEM_FK3 
  FOREIGN KEY (REF_ATRIB_SCENR_NOTFC) 
  REFERENCES AFW_12_ATRIB_SCENR_NOTFC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
