SET DEFINE OFF;
ALTER TABLE AFW_23_APLIC_MODL_RECHR ADD (
  CONSTRAINT AFW_23_APLIC_MODL_RECHR_FK2 
  FOREIGN KEY (REF_STRUC_APLIC_RECHR) 
  REFERENCES AFW_12_STRUC_APLIC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
