SET DEFINE OFF;
ALTER TABLE AFW_13_PAGE_ITEM_LANG ADD (
  CONSTRAINT AFW_13_PAGE_ITEM_LANG_FK1 
  FOREIGN KEY (REF_PAGE_ITEM) 
  REFERENCES AFW_13_PAGE_ITEM (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
