SET DEFINE OFF;
ALTER TABLE AFW_12_DEFNT_ACCES ADD (
  CONSTRAINT AFW_12_DEFNT_ACCES_CK1
  CHECK ((    REF_GROUP_UTILS IS NOT NULL    AND       REF_UTILS IS NULL  )  OR  (    REF_GROUP_UTILS IS NULL    AND       REF_UTILS IS NOT NULL  ))
  ENABLE VALIDATE)
/
