SET DEFINE OFF;
ALTER TABLE AFW_12_LIEN_GROUP_UTILS ADD (
  CONSTRAINT AFW_12_LIEN_GROUP_UTILS_CK1
  CHECK (
  (    REF_GROUP_UTILS_LIE IS NOT NULL    AND    REF_UTILS IS NULL )
  OR
  (    REF_GROUP_UTILS_LIE IS NULL    AND    REF_UTILS IS NOT NULL )
 )
  ENABLE VALIDATE)
/
