SET DEFINE OFF;
ALTER TABLE AFW_01_CONFG_EVENM_NOTFB_LANG ADD (
  CONSTRAINT AFW_01_CONFG_EVENM_NOTFB_L_FK1 
  FOREIGN KEY (REF_CONFG_EVENM_NOTFB) 
  REFERENCES AFW_01_CONFG_EVENM_NOTFB (SEQNC)
  ENABLE VALIDATE)
/
