SET DEFINE OFF;
ALTER TABLE AFW_12_REQT_INTER_UTILS ADD (
  CONSTRAINT AFW_12_REQT_INTER_UTILS_FK1 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES AFW_12_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
