SET DEFINE OFF;
ALTER TABLE AFW_25_ENGIN_VERSN_PUBLC ADD (
  CONSTRAINT AFW_25_ENGIN_VERSN_PUBLC_FK1 
  FOREIGN KEY (REF_VERSN_PUBLC) 
  REFERENCES AFW_25_VERSN_PUBLC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
