SET DEFINE OFF;
ALTER TABLE AFW_23_RESLT_RECHR ADD (
  CONSTRAINT AFW_23_RESLT_RECHR_FK2 
  FOREIGN KEY (REF_APLIC_MODL_RECHR) 
  REFERENCES AFW_23_APLIC_MODL_RECHR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
