SET DEFINE OFF;
ALTER TABLE AFW_25_PARMT_PUBLC_TRAVL ADD (
  CONSTRAINT AFW_25_PARMT_PUBLC_TRAVL_FK2 
  FOREIGN KEY (REF_PARMT_TYPE_PUBLC) 
  REFERENCES AFW_25_PARMT_TYPE_PUBLC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
