SET DEFINE OFF;
ALTER TABLE AFW_21_PLUGN_ITEM_MENU ADD (
  CONSTRAINT AFW_21_PLUGN_ITEM_MENU_FK1 
  FOREIGN KEY (REF_ITEM_MENU) 
  REFERENCES AFW_13_ITEM_MENU (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
