SET DEFINE OFF;
ALTER TABLE AFW_23_DETL_RESLT_RECHR ADD (
  CONSTRAINT AFW_23_DETL_RESLT_RECHR_FK3 
  FOREIGN KEY (REF_DETL_APLIC_MODL_RECHR) 
  REFERENCES AFW_23_DETL_APLIC_MODL_RECHR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
