SET DEFINE OFF;
ALTER TABLE AFW_12_MEMBR_STRUC ADD (
  CONSTRAINT AFW_12_MEMBR_STRUC_FK2 
  FOREIGN KEY (REF_STRUC_ADMIN) 
  REFERENCES AFW_12_STRUC_ADMIN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
