SET DEFINE OFF;
ALTER TABLE AFW_01_MODL_COMNC ADD (
  CONSTRAINT AFW_01_MODL_COMNC_FK1 
  FOREIGN KEY (REF_TYPE_COMNC) 
  REFERENCES AFW_01_TYPE_COMNC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
