SET DEFINE OFF;
ALTER TABLE AFW_01_MODL_AFICH_NOTFC ADD (
  CONSTRAINT AFW_01_MODL_AFICH_NOTFC_FK6 
  FOREIGN KEY (REF_MODL_COMNC) 
  REFERENCES AFW_01_MODL_COMNC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
