SET DEFINE OFF;
ALTER TABLE AFW_07_AUDIT_STRUC_APLIC ADD (
  CONSTRAINT AFW_07_AUDIT_STRUC_APLIC_FK4 
  FOREIGN KEY (REF_PAGE) 
  REFERENCES AFW_13_PAGE (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
