SET DEFINE OFF;
ALTER TABLE AFW_12_LIEN_GROUP_UTILS ADD (
  CONSTRAINT AFW_12_LIEN_GROUP_UTILS_FK1 
  FOREIGN KEY (REF_GROUP) 
  REFERENCES AFW_12_GROUP_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
