SET DEFINE OFF;
ALTER TABLE AFW_13_REGN_PILTB_LANG ADD (
  CONSTRAINT AFW_13_REGN_PILTB_LANG_FK1 
  FOREIGN KEY (REF_REGN_PILTB) 
  REFERENCES AFW_13_REGN_PILTB (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
