SET DEFINE OFF;
ALTER TABLE AFW_12_LIEN_GROUP_UTILS ADD (
  CONSTRAINT AFW_12_LIEN_GROUP_UTILS_FK2 
  FOREIGN KEY (REF_UTILS) 
  REFERENCES AFW_12_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
