SET DEFINE OFF;
ALTER TABLE AFW_21_PLUGN_ITEM_MENU ADD (
  CONSTRAINT AFW_21_PLUGN_ITEM_MENU_FK3 
  FOREIGN KEY (REF_DV_CONTN_ITEM_MENU) 
  REFERENCES AFW_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE)
/
