SET DEFINE OFF;
ALTER TABLE AFW_37_LIEN_GADGT_PARMT_RACRC ADD (
  CONSTRAINT AFW_37_LIEN_GADGT_PARMT_R_FK1 
  FOREIGN KEY (REF_GADGT_PARMT_RACRC) 
  REFERENCES AFW_37_GADGT_PARMT_RACRC (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
