SET DEFINE OFF;
ALTER TABLE AFW_01_HIERC_APLIC ADD (
  CONSTRAINT AFW_12_HIERC_APLIC_FK1 
  FOREIGN KEY (REF_EVENM_NOTFB) 
  REFERENCES AFW_01_EVENM_NOTFB (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
