SET DEFINE OFF;
ALTER TABLE AFW_12_REQT_INTER_UTILS ADD (
  CONSTRAINT AFW_12_REQT_INTER_UTILS_FK4 
  FOREIGN KEY (REF_PRODT) 
  REFERENCES AFW_11_PRODT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
