SET DEFINE OFF;
ALTER TABLE AFW_12_REQT_INTER_UTILS ADD (
  CONSTRAINT AFW_12_REQT_INTER_UTILS_FK2 
  FOREIGN KEY (REF_DV_TYPE_REQT_INTER) 
  REFERENCES AFW_14_DETL_DOMN_VALR (SEQNC)
  ENABLE VALIDATE)
/
