SET DEFINE OFF;
ALTER TABLE AFW_37_LIEN_GADGT_PARMT_RACRC ADD (
  CONSTRAINT AFW_37_LIEN_GADGT_PARMT_R_FK2 
  FOREIGN KEY (REF_GADGT_PARMT) 
  REFERENCES AFW_37_GADGT_PARMT (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
