SET DEFINE OFF;
ALTER TABLE AFW_12_GR_UT_OPERT_OPTIO_DOMN ADD (
  CONSTRAINT AFW_12_GU_OPER_OPT_DOMN_FK1 
  FOREIGN KEY (REF_GROUP_UTILS) 
  REFERENCES AFW_12_GROUP_UTILS (SEQNC)
  ENABLE VALIDATE)
/
