SET DEFINE OFF;
ALTER TABLE AFW_13_ITEM_MENU ADD (
  CONSTRAINT AFW_13_ITEM_MENU_FK18 
  FOREIGN KEY (REF_STRUC_APLIC) 
  REFERENCES AFW_12_STRUC_APLIC (SEQNC)
  ON DELETE SET NULL
  ENABLE VALIDATE)
/
