SET DEFINE OFF;
ALTER TABLE AFW_12_LIEN_GADGT_UTILS ADD (
  CONSTRAINT AFW_12_LIEN_GADGT_UTILS_FK2 
  FOREIGN KEY (REF_SESN) 
  REFERENCES AFW_12_SESN (ID_SESN)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
