SET DEFINE OFF;
ALTER TABLE AFW_13_INSTA_REGN_PILTB ADD (
  CONSTRAINT AFW_13_INSTA_REGN_PILTB_FK2 
  FOREIGN KEY (REF_REGN_PILTB) 
  REFERENCES AFW_13_REGN_PILTB (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
