SET DEFINE OFF;
ALTER TABLE AFW_12_DOMN_SERVR_LDAP ADD (
  CONSTRAINT AFW_12_DOMN_SERVR_LDAP_FK1 
  FOREIGN KEY (REF_SERVR_LDAP) 
  REFERENCES AFW_12_SERVR_LDAP (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
