SET DEFINE OFF;
ALTER TABLE AFW_04_FIL_ARIAN ADD (
  CONSTRAINT AFW_04_FIL_ARIAN_FK3 
  FOREIGN KEY (REF_NAVGT_HISTR) 
  REFERENCES AFW_04_NAVGT_HISTR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
