SET DEFINE OFF;
ALTER TABLE AFW_23_DETL_APLIC_MODL_RECHR ADD (
  CONSTRAINT AFW_23_DETL_APLIC_MODL_REC_FK3 
  FOREIGN KEY (REF_PATRN_RECHR) 
  REFERENCES AFW_23_PATRN_RECHR (SEQNC)
  ENABLE VALIDATE)
/
