SET DEFINE OFF;
ALTER TABLE AFW_36_VUE_TRI_SECND ADD (
  CONSTRAINT AFW_36_VUE_TRI_SECND_FK3 
  FOREIGN KEY (REF_ATRIB) 
  REFERENCES AFW_36_ATRIB_DISPN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
