SET DEFINE OFF;
ALTER TABLE AFW_36_LIEN_OPERT_FILTR ADD (
  CONSTRAINT AFW_36_LIEN_OPERT_FILTR_FK1 
  FOREIGN KEY (REF_OPERT_FILTR) 
  REFERENCES AFW_36_OPERT_FILTR (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
