SET DEFINE OFF;
ALTER TABLE AFW_12_INSTA_REGLE_APROB ADD (
  CONSTRAINT AFW_12_INSTA_REGLE_APROB_FK2 
  FOREIGN KEY (REF_REGLE_APROB) 
  REFERENCES AFW_12_REGLE_APROB (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
