SET DEFINE OFF;
ALTER TABLE AFW_13_EMPLA_DOSR_VIRTL ADD (
  CONSTRAINT AFW_13_EMPLA_DOSR_VIRTL_FK2 
  FOREIGN KEY (REF_VERSN) 
  REFERENCES AFW_11_VERSN (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
