SET DEFINE OFF;
ALTER TABLE AFW_23_DETL_APLIC_MODL_RECHR ADD (
  CONSTRAINT AFW_23_DETL_APLIC_MODL_REC_UK1
  UNIQUE (REF_APLIC_MODL_RECHR, REF_ATRIB_STRUC_APLIC, REF_PATRN_RECHR, PERTN)
  ENABLE VALIDATE)
/
