SET DEFINE OFF;
ALTER TABLE AFW_12_DEFNT_ACCES ADD (
  CONSTRAINT AFW_12_DEFNT_ACCES_FK2 
  FOREIGN KEY (REF_GROUP_UTILS) 
  REFERENCES AFW_12_GROUP_UTILS (SEQNC)
  ON DELETE CASCADE
  ENABLE VALIDATE)
/
