GRANT INSERT ON APEX_050000.WWV_FLOW_AUTHENTICATIONS TO APEXFRAMEWORK
/
GRANT INSERT, SELECT, UPDATE ON APEX_050000.WWV_FLOW_BUTTON_TEMPLATES TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_COMPANIES TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_COMPANY_SCHEMAS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_COMPUTATIONS TO APEXFRAMEWORK
/
GRANT EXECUTE ON APEX_050000.WWV_FLOW_CONDITIONS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_CUSTOM_AUTH_SETUPS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_DATA TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_DATA_LOAD_BAD_LOG TO APEXFRAMEWORK
/
GRANT DELETE, SELECT ON APEX_050000.WWV_FLOW_DATA_LOAD_UNLOAD TO APEXFRAMEWORK
/
GRANT INSERT, SELECT, UPDATE ON APEX_050000.WWV_FLOW_FIELD_TEMPLATES TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_FLASH_CHART5_SERIES TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_FLASH_CHARTS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_FLASH_CHARTS_5 TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_FLASH_CHART_SERIES TO APEXFRAMEWORK
/
GRANT EXECUTE ON APEX_050000.WWV_FLOW_GEN_API2 TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_ICON_BAR TO APEXFRAMEWORK
/
GRANT INSERT, SELECT ON APEX_050000.WWV_FLOW_ITEMS TO APEXFRAMEWORK
/
GRANT EXECUTE ON APEX_050000.WWV_FLOW_JAVASCRIPT TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_LANGUAGE_MAP TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_LIST_ITEMS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_LIST_OF_VALUES_DATA TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_LISTS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_LISTS_OF_VALUES$ TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_LIST_TEMPLATES TO APEXFRAMEWORK
/
GRANT EXECUTE ON APEX_050000.WWV_FLOW_LOAD_DATA TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_MENU_OPTIONS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_MENUS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_MENU_TEMPLATES TO APEXFRAMEWORK
/
GRANT DELETE, INSERT, SELECT ON APEX_050000.WWV_FLOW_MESSAGES$ TO APEXFRAMEWORK
/
GRANT DELETE, INSERT, SELECT ON APEX_050000.WWV_FLOW_PAGE_DA_ACTIONS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_PAGE_DA_EVENTS TO APEXFRAMEWORK
/
GRANT INSERT, SELECT, UPDATE ON APEX_050000.WWV_FLOW_PAGE_PLUGS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_PAGE_PLUG_TEMPLATES TO APEXFRAMEWORK
/
GRANT DELETE, SELECT ON APEX_050000.WWV_FLOW_PAGE_SUBMISSIONS TO APEXFRAMEWORK
/
GRANT INSERT, SELECT ON APEX_050000.WWV_FLOW_PLUGIN_ATTRIBUTES TO APEXFRAMEWORK
/
GRANT INSERT, SELECT ON APEX_050000.WWV_FLOW_PLUGIN_ATTR_VALUES TO APEXFRAMEWORK
/
GRANT INSERT ON APEX_050000.WWV_FLOW_PLUGIN_EVENTS TO APEXFRAMEWORK
/
GRANT INSERT ON APEX_050000.WWV_FLOW_PLUGIN_FILES TO APEXFRAMEWORK
/
GRANT INSERT, SELECT ON APEX_050000.WWV_FLOW_PLUGINS TO APEXFRAMEWORK
/
GRANT INSERT, SELECT ON APEX_050000.WWV_FLOW_PLUGIN_SETTINGS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_POPUP_LOV_TEMPLATE TO APEXFRAMEWORK
/
GRANT INSERT, SELECT ON APEX_050000.WWV_FLOW_PROCESSING TO APEXFRAMEWORK
/
GRANT INSERT, SELECT, UPDATE ON APEX_050000.WWV_FLOW_REGION_REPORT_COLUMN TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_REGION_UPD_RPT_COLS TO APEXFRAMEWORK
/
GRANT EXECUTE ON APEX_050000.WWV_FLOW_RENDER_QUERY TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_ROW_TEMPLATES TO APEXFRAMEWORK
/
GRANT SELECT, UPDATE ON APEX_050000.WWV_FLOWS TO APEXFRAMEWORK
/
GRANT EXECUTE ON APEX_050000.WWV_FLOW_SECURITY TO APEXFRAMEWORK
/
GRANT INSERT, SELECT, UPDATE ON APEX_050000.WWV_FLOW_SECURITY_SCHEMES TO APEXFRAMEWORK
/
GRANT REFERENCES, SELECT ON APEX_050000.WWV_FLOW_SESSIONS$ TO APEXFRAMEWORK
/
GRANT INSERT, SELECT ON APEX_050000.WWV_FLOW_SHORTCUTS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_STEP_BRANCHES TO APEXFRAMEWORK
/
GRANT INSERT, SELECT, UPDATE ON APEX_050000.WWV_FLOW_STEP_BUTTONS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_STEP_COMPUTATIONS TO APEXFRAMEWORK
/
GRANT SELECT, UPDATE ON APEX_050000.WWV_FLOW_STEP_ITEMS TO APEXFRAMEWORK WITH GRANT OPTION
/
GRANT INSERT ON APEX_050000.WWV_FLOW_STEP_ITEMS TO APEXFRAMEWORK
/
GRANT INSERT, SELECT, UPDATE ON APEX_050000.WWV_FLOW_STEP_PROCESSING TO APEXFRAMEWORK
/
GRANT INSERT, SELECT, UPDATE ON APEX_050000.WWV_FLOW_STEPS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_TABS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_TEMPLATES TO APEXFRAMEWORK
/
GRANT INSERT, SELECT, UPDATE ON APEX_050000.WWV_FLOW_THEMES TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_TREES TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_USER_INTERFACES TO APEXFRAMEWORK
/
GRANT EXECUTE ON APEX_050000.WWV_FLOW_WIZARD_API TO APEXFRAMEWORK
/
GRANT EXECUTE ON APEX_050000.WWV_FLOW_WORKSHEET TO APEXFRAMEWORK
/
GRANT EXECUTE ON APEX_050000.WWV_FLOW_WORKSHEET_API TO APEXFRAMEWORK
/
GRANT INSERT, SELECT, UPDATE ON APEX_050000.WWV_FLOW_WORKSHEET_COLUMNS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_WORKSHEET_COMPUTATION TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_WORKSHEET_CONDITIONS TO APEXFRAMEWORK
/
GRANT SELECT ON APEX_050000.WWV_FLOW_WORKSHEET_RPTS TO APEXFRAMEWORK
/
GRANT INSERT, SELECT, UPDATE ON APEX_050000.WWV_FLOW_WORKSHEETS TO APEXFRAMEWORK
/
GRANT EXECUTE ON APEX_050000.WWV_FLOW_WORKSHEET_STANDARD TO APEXFRAMEWORK
/
GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON FLOWS_FILES.WWV_FLOW_FILE_OBJECTS$ TO APEXFRAMEWORK
/